### ISSUE TITLE
Add E2E Test Suite / Example

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#115]
We should write a test suite using this framework that validates that the integration between Synthetics / Heartbeat / ES / Kibana all works together. We can run the examples in this repo for this, and orchestrate using docker compose.

**Comment by paulb-elastic** [comment]
ACs:
- Deploys docker image
- Runs the monitors in the `examples` folder (which populates data in ES)
- Run Kibana and check that the results exist in Uptime (within a reasonable timeout)

**Comment by vigneshshanmugam** [comment]
Done with #148 #116
