### ISSUE TITLE
Journey start/end timestamps are incorrect

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#118]
It looks like we're setting the start/end timestamps for journeys in the JSON to the same value from the journey context. This makes calculating journey duration impossible. This can be confirmed with the following command

```bash
andrewvc@x1e:~/p/s/e/todos|example-reliability⚡*?
➤ npx @elastic/synthetics . --json | jq '{t: .type, ts: .["@timestamp"]} | select(.t | contains("journey"))' -c
{"t":"journey/start","ts":1604025562618983}
{"t":"journey/end","ts":1604025562618983}
{"t":"journey/start","ts":1604025563206505.2}
{"t":"journey/end","ts":1604025563206505.2}
{"t":"journey/start","ts":1604025563766296.5}
{"t":"journey/end","ts":1604025563766296.5}
{"t":"journey/start","ts":1604025564166952}
{"t":"journey/end","ts":1604025564166952}
```

**Comment by jahtalab** [comment]
Summary from the slack thread: 

We shouldn't use timestamps for calculating the duration, instead we should use the high resolution monotonic clock (in start/end) for that

**Comment by jahtalab** [comment]
Tech sync:
- We should fix the timestamp on all events to be the time they were created
- We should use the highres monotonic clock to drive the timestamp
- For devtools events we need to adjust the timestamp based on the clock passed from devtools

**Comment by andrewvc** [comment]
To summarize our latest discussion, we do want to make these timestamps possible to use to calculate duration (with the caveat that they are limited to millisecond precision).
