### ISSUE TITLE
Capture relevant perf metrics to close the gap with RUM agent

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#120]
This has come up multiple times in the slack channel. We have to measure and report all the performance metrics for each step session. 

#### Metrics to meausre
   - [x] First Contentful Paint (FCP)
   - [x] Core Web Vital: Largest Contentful Paint (LCP)
   - [x] Core Web Vital: Cumulative Layout Shift (CLS)
   - [x] onLoad (document complete)
   - [x] DOM Content Loaded
   - [x] User timing marks & measures

**Note: The above marked items are fixed by PR #194**

More details - https://github.com/elastic/uptime/issues/250

**Comment by paulb-elastic** [comment]
@vigneshshanmugam can you convert the above list into checkboxes and mark off the ones that have been done, to make it easier to identify what status this is in, thanks.

**Comment by paulb-elastic** [comment]
I have removed these from the main issue as they can all be calculated.  If necessary, a separate issue will be created if these need to be optimised when we come to use them:
* Number of Requests
* Bytes Over the Wire
* Bytes Uncompressed
* Connected Domains

**Comment by paulb-elastic** [comment]
Split off some of the metrics into separate issue https://github.com/elastic/synthetics/issues/283
