### ISSUE TITLE
Feature flag to control filmstrip image capture

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#143]
Until filmstrips are implemented (https://github.com/elastic/kibana/issues/83816), we want to change the default behaviour of the Synthetic Agent to stop capturing filmstrip images, to avoid any impact of them, or incorrect timestamps.  Similarly, we want the ability to do filmstrip capture testing, so will be able to switch them on with a feature flag.

**Acceptance criteria**
- [ ] By default, the Synthetics Agent will not capture filmstrip images
- [ ] There is a configuration option that, when enabled, will make the Synthetics Agent capture filmstrip images (in the same way that it does currently)

**Comment by jahtalab** [comment]
To clarify, we currently have the `screenshots` option that is used for both step screenshots and filmstrip, so we need to separate these.

**Comment by paulb-elastic** [comment]
Thanks @jahtalab, didn't realise it was the same process used for both (I thought we captured a screen shot on step complete).

That's correct, irrespective of this feature, we still need to have final screen shot for all steps, as we do now.

**Comment by vigneshshanmugam** [comment]
This is already done btw - https://github.com/elastic/synthetics/pull/121 😄

**Comment by jahtalab** [comment]
Thanks @vigneshshanmugam , I merged the PR.
