### ISSUE TITLE
Do not download updates by default

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#144]
**Requirement**
As a user of Elastic Synthetics in an environment without internet access
I want an option to prevent Synthetics from updating from the internet
So that I can use Synthetics based on the version I have installed

In reality, this will mostly be used in the docker version of the Synthetics Agent, as this already contains all of the components needed to run a test.  However, this should be a Synthetics Agent option (which can be passed in to a docker run as well), which in theory could still be used if all the components and NPM packages had been installed manually somehow in the environment without internet access.

**This specifically relates to inline monitors** (those defined in the `heartbeat.yml`) as suites are handled differently.  In the case of suites, an npm install has to run to ensure any dependencies in the `package.json` have been met (e.g. a user could add a new requirement for an additional node module for something they are doing in the script).  The user is in full control of the `package.json`, which includes any versions of any packages (as well as Synthetics).

**Acceptance Criteria**
* A configuration/parameter option to prevent the Synthetics Agent from attempting to update any component (Playwright, Chromium, Synthetics library etc.)
* By default, updates will be disabled
* When updates are disabled (the default), the Agent will attempt to run with the components available and not download or update any from the internet
* When updates are enabled, the Synthetics Agent will do what it does now, looking for updates when run

@jahtalab has pointed out this area of the code to modify behaviour: https://github.com/elastic/beats/blob/heartbeat-synthetics/x-pack/heartbeat/monitors/browser/synthexec/synthexec.go#L57

**Comment by vigneshshanmugam** [comment]
This is an interesting issue and there is an alternative solution to this problem to the one proposed above. 

We control the installation through environment variable for air gapped and other for non air gapped environments.

## Solution to air gapped environments

For air gapped env, an easier solution would to use the browsers from local `node_modules` directory and use the same for all packages that synthetics library depend on. The node_modules directory would be available already in the docker image (This would mean heartbeat machine does not need access to internet to download playwright/browser updates and other packages). 

With each update of the Node.js synthetics library, we release a new docker image with modified versions of playwright if required and we could still keep the compatibility going on as usual. The disadvantage of not updating the docker image regularly, still exists but if users needs new features, then we ask them to update the images regularly like every other Elastic stack update.

## Solution to non air gapped env

For non air gapped env, we always rely on the latest version of the Node.js synthetic library which would install the pinned playwright versions. This would work like how its working right now in master branch.

**Comment by vigneshshanmugam** [comment]
Did some work on this branch to make it work with locally installed node_modules. https://github.com/vigneshshanmugam/synthetics/tree/local-packages/examples

**Comment by paulb-elastic** [comment]
I have updated the title and requirement definition slightly, after some discussions about this with @andrewvc.

This requirement specifically relates to inline monitors, as suites are handled separately, via the `package.json`, for which an npm install will need to happen (as the user may have added additional dependencies).  This will include the version of Synthetics (either any, or a specific version), and as such is user the user's control.

**Comment by paulb-elastic** [comment]
For reference, https://github.com/elastic/observability-docs/issues/284 will document more detail about how the `package.json` works and should be used.
