### ISSUE TITLE
Add support for junit file output

### ISSUE THREAD

**Issue by shahzad31** [elastic/synthetics#149]
We should add support for junit file output, that will make it easy to integerate synthetics test into CI

**Comment by shahzad31** [comment]
we can use something like this perhaps 
https://github.com/microsoft/playwright-test

example:
`npx folio --reporter=junit,line`

**Comment by vigneshshanmugam** [comment]
We dont support custom reporters at the moment other than the `base` and `json`, However it depends if we want to go via the path of being a test runner vs a synthetic tool.

**Comment by andrewvc** [comment]
I personally love the idea of a JUnit reporter, IMHO we want to do both. Write the test locally, run it in CI, then deploy it to production. CC @paulb-elastic @drewpost

**Comment by shahzad31** [comment]
can we please prioritise this, while integrating into CI, it's always a guess which format to use to get elastic/synthetics tests output .

@v1v faced the same problem.
