### ISSUE TITLE
capture more network information to improve waterfall

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#152]
Couple of improvements that we can do to improve the step level waterfall in the UI
+ [x] Move the overall timing calculation logic in the UI to the agent to improve the performance #168 
+ [x] Use `requestSentime` and `responseReceivedTime` in favor of `start/end` time and use the monotonic clock in start
and end time
+ [x] Capture the step index info for all the netinfo events to make querying easier 
+ [x] Fix the timestamp to get the value of when the event got generated vs when the event is written to stdout which is after journey end.
~+ [ ] Enhance the additional headers information by listening to `requestWillBeSentExtraInfo` and `responseReceivedExtraInfo` event~
~+ [ ] Figure out if an entry is from the cache by using `requestServedFromCache` event.~

**Comment by paulb-elastic** [comment]
Removing `capture web vitals and other RUM metrics - #120` from the list of requirements as we're tracking #120 separately.

**Comment by andrewvc** [comment]
Since we don't actually need the last two items for our UI right now I've crossed this out, and am closing the issue.
