### ISSUE TITLE
Docker example doesn't work well with uids != 1000

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#156]
In elastic/synthetics#153  @paulb-elastic discovered that the docs only work in the rather common scenario where the your user on the host machine is 1000 which matches the heartbeat user in the container. The issue, essentially, is that the `heartbeat` user in docker has a uid of `1000`, and if this doesn't match up with the uids of the shared mounts you'll get perms issues.

Possible solutions:

1. Document this, recommend users users change their local file perms
2. Start using [fixuid](https://github.com/boxboat/fixuid) in the container
3. Something else???

**Comment by paulb-elastic** [comment]
During tech sync we have discussed the option of using a copy on start up, as opposed to a shared volume.

In this way, the host folder would be copied into the container at start up (which only needs read permissions) and then the runtime Synthetics Agent uses that folder inside the container (not as a shared volume).  It will of course be ephemeral and do the same during the next launch.

The [Remote Zip URL support](https://github.com/elastic/uptime/issues/271) feature will still provide a mechanism for the suites to be updated without needing a shared volume.

Similarly, [hot reloading](https://github.com/elastic/beats/issues/22511) would still be supported in that it would just periodically copy the host folder(s) to the running container at the given interval.
