### ISSUE TITLE
journey/network_info events are sometimes associated with the wrong step.index

### ISSUE THREAD

**Issue by Kerry350** [elastic/synthetics#165]
(The Agent was run via Docker with `./run.sh 8.0.0` for the following)

Given a query like this, it's **sometimes** possible to have no `journey/network_info` documents returned.

In this exact scenario it returned me a `step/end` (`status: succeeded`) document and a `step/screenshot` document.

```
{
   "query":{
      "bool":{
         "filter":[
            {
               "term":{
                  "monitor.check_group":"a654b2f5-3881-11eb-80b5-025000000001"
               }
            },
            {
               "term":{
                  "synthetics.step.index":1
               }
            }
         ]
      }
   }
}
```

This is a `check_group` which contains 2 steps. Both steps should contain network info.

Those "missing" `journey/network_info` documents for step 1, seem to get associated to step 2. This would suggest there's a bug in the way the network info events are being associated to their `step.index`.

This doesn't happen all of the time, it's only some journey runs, suggesting the timing skew is quite subtle somewhere.

**Comment by vigneshshanmugam** [comment]
I have tried to reproduce this multiple times and have not succeeded. @Kerry350 Do you think this could be fixed along with our recent fix in step timings?

**Comment by vigneshshanmugam** [comment]
Closing this as not reproducible, Will reopen if we see this in future.
