### ISSUE TITLE
Support custom cert store

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#170]
We should support some simple way of supporting custom certs for playwright. See https://github.com/microsoft/playwright/issues/1799#issuecomment-731734494 for more info.

**Comment by a03nikki** [comment]
As a temporary work around, build a custom container based on the official one. The private certificate authority (CA) file needs to be  copied to `/usr/share/pki/ca-trust-source/anchors/` and then the `/usr/bin/update-ca-trust` command needs to be ran as root, all before Heartbeat starts.

**Comment by andrewvc** [comment]
We've documented @a03nikki 's approach here: https://github.com/elastic/synthetics/blob/master/examples/todos/Dockerfile#L20 .

Ideally there'd be a way to do this in a more streamlined way, just running the `update-ca-trust` command automatically, only requiring the user to share the file into the anchors folder.

It doesn't seem like there's any way to adjust the CA store just for the browser rather than for the whole system. @vigneshshanmugam @jahtalab do you know of any way to do this without requiring root?

**Comment by philippkahr** [comment]
Since we changed to Ubuntu as a basis for the docker images, the command changed from `update-ca-trust` to `update-ca-certificates`

**Comment by beantoast** [comment]
This workaround work for me on ubuntu image:

Login as root to run:
`apt update && apt install libnss3-tools`
 
Exit and login as elastic-agent and run 
`certutil -A -n "<cert_nick_name>" -d ~/.pki/nssdb -t C,, -a -i <cert_location>.crt`

**Comment by paulb-elastic** [comment]
Linking https://github.com/elastic/synthetics/issues/717

**Comment by paulb-elastic** [comment]
A recent discussion also led to one idea being to include custom CAs when pushing configurations.

**Comment by Jaraxal** [comment]
+1 

Does this issue incorporate the ability for Synthetics to support certificate-based authentication, or would that be a separate issue?

**Comment by andrewvc** [comment]
@Jaraxal for lightweight monitors that is very readily supported. For browser monitors with playwright it's [a bit tricky](https://github.com/microsoft/playwright/issues/1799#issuecomment-731734494)

**Comment by graphaelli** [comment]
Will this approach change again with the move to wofli images?

**Comment by wortmanb** [comment]
Clusters on air-gapped networks with PKI are going to need this badly.

**Comment by felix-lessoer** [comment]
Playwright is supporting this option in their version 1.46 -- https://playwright.dev/docs/next/api/class-browser#browser-new-context-option-client-certificates

Which version are we running and when can we expect to make it available in Elastic Synthetics?

**Comment by shahzad31** [comment]
@felix-lessoer 
we are on =1.45.1 at the moment, we can consider upgrading to 1.46.0 , what do you think @vigneshshanmugam @emilioalvap ??

**Comment by emilioalvap** [comment]
> Which version are we running and when can we expect to make it available in Elastic Synthetics?

@felix-lessoer In-memory certificates will land on a upcomingPW release, we might be able to extend Elastic Synthetics to support it then. cc @drewpost @andrewvc @vigneshshanmugam @graphaelli 

> Will this approach change again with the move to wofli images?
@graphaelli It shouldn't, Chromium should use nss store regardless of the distro. The tools required to manually edit the storage do vary across distros.

**Comment by shahzad31** [comment]
shipped with https://github.com/elastic/synthetics/releases/tag/v1.13.0

**Comment by vigneshshanmugam** [comment]
Keeping this as open till we have the necessary docs in place which should cover both Elastic managed locations and also private locations.

**Comment by vigneshshanmugam** [comment]
https://github.com/elastic/observability-docs/pull/4351
