### ISSUE TITLE
Add `ignoreHTTPSError` option on journeys and CLI

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#171]
Users sometimes need to test sites that have known bad certs, we should probably  set this on a per-journey and CLI options level, both probably have their uses. See https://github.com/microsoft/playwright/issues/2814 for more info on implementation, it's a browser level option.

**Comment by vigneshshanmugam** [comment]
We could start supporting chrome flags and other options when launching suites. Could also work for our emulation strategy if we are going to depend on devtools emulation for network and cpu slowdown.

**Comment by shahidmgr** [comment]
Hey, @andrewvc  and @vigneshshanmugam any fix of this using Synthetic run.
