### ISSUE TITLE
Redirects and DNS failures not represented correctly

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#175]
The waterfall chart is not showing **redirects** or **DNS failure** requests correctly.  These are implemented differently within the Chrome events, so likely that we are not extracting these requests correctly for storing into ES for displaying on the waterfall chart.

Issues:
* DNS failures
  * There is a row in the waterfall chart for the domain/request, but no chart data showing the DNS lookup time (which happens to fail)
* Redirects are not shown at all
  * There is no row in the waterfall chart

![image](https://user-images.githubusercontent.com/70908889/102515077-32ada180-4085-11eb-8d06-f92a7b1a0ccc.png)

**Comment by vigneshshanmugam** [comment]
The redirect issue is a bug in the agent as we override the record of the event. CDP issues the event with the same request id for both of the redirected request and also the proper request. Will have to do a proper fix.

**Comment by vigneshshanmugam** [comment]
For the DNS failure, there is `timings.total` which should be used instead, Guess that would be fixed along with the squished waterfall PR that @dominiqueclarke is working on. The redirect issue would be fixed by this PR #180
