### ISSUE TITLE
Provide integration with lighthouse audits

### ISSUE THREAD

**Issue by jahtalab** [elastic/synthetics#176]
Lighthouse provides a set of performance audits, these in turn can be used to generate actionable results for optimisation in the synthetics UI. The following audits is a good place to start:

- [third-party JavaScript audit](https://web.dev/identify-slow-third-party-javascript/) provides list of JS resources that impact the page performance the most. This includes their Main thread and parse times. This audit can show users which scripts they should focus on for optimisation 
- [critical requests chain detection](https://web.dev/critical-request-chains/)

 @paulb-elastic @drewpost thoughts?

**Comment by paulb-elastic** [comment]
I like the idea of a performance audit that provides the most useful optimisations to focus on first.  These could be powered by different analysis “engines”, e.g. a Lighthouse audit, those you listed, image optimisations etc.

We’d want to think about how this fits in with synthetic monitoring. For example, I would suggest that you wouldn’t want to run this for every monitor (imaging a 5 minute frequency monitor, there’s little value in auditing every single run).

What might be more useful is for them to be on a different schedule - e.g. a performance audit schedule as opposed to a monitoring schedule.  We’d also want to think about how (and where) this fits into the UI/reporting (e.g. maybe a separate performance audit focused area, that we can build on over time).

In addition to these being scheduled, you could imagine running these on demand (ad hoc).  Maybe this is triggered by someone providing a URL, or for a more integrated solution - you could press an “audit” button from one of your monitors, or from RUM data, where you get an audit for the thing you’re investigating.

**Comment by andrewvc** [comment]
I like this as well, and it dovetails with the idea of a single page mode, without all the automation, where you just specify a URL, no scripting, and then get the perf. 

How do you see this working at a product level @jahtalab ? How would users interact with it and operationalize it?

**Comment by jahtalab** [comment]
I think we can use these audits to generate suggestions for optimising the application. We don't necessary need to show these audits in the raw format (although we can if users want to) but instead to generate a suggested todo list of items that are most likely to improve users' application performance. This can even be combined with RUM data to generate an estimated performance gain. For example, from the RUM data we have the resources and their impact on each page, and with cross-referencing with audit result we can generate an estimate. I think @drewpost also presented a page in the road map that can be a good fit for this data.
