### ISSUE TITLE
Provide a correlation id for tracking journey to apm traces

### ISSUE THREAD

**Issue by mikeh-elastic** [elastic/synthetics#178]
Having the synthetics journey add somethings that can be captured by apm agents would be helpful to tie these information sources together.

For example having 3 levels of metadata:

group: app-a
agent: actual-agent-identifier
uuid: the unique id for this synthetic journey

Would allow filtering on groups of agents working together, all runs by a particular agent, or a unique journey into the apm portion of observability to identify the actual traces that serviced this journey.  From the apm traces the trace.id could be correlated to logs and from the hostname of the infrastructure running the code to metrics of what serviced the applications.  The reverse journey should also be possible metrics/logs->apm->synthetic journeys.

**Comment by vigneshshanmugam** [comment]
Closing this issue as its covered by #265 #245
