### ISSUE TITLE
Migrate examples to use heartbeat snapshot docker containers instead of experimental synthetics ones

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#182]
With https://github.com/elastic/beats/pull/23274 merged into master the heartbeat x-pack docker snapshot image for master is the heartbeat synthetics image. When  https://github.com/elastic/beats/pull/23380 is merged that will be the case for 7.x as well. 7.12 will be the first release to container synthetics in a non-snapshot docker image.

I'm thinking the best strategy would be to do the following:

- [ ] Prior to 7.11 being released update our examples/run.sh to use `docker.elastic.co/beats/heartbeat:7.x-SNAPSHOT` by default
- [ ] For 7.12 update our examples/run.sh to use the latest non-snapshot stack version
- [ ] Find a way for synthetics development to allow easy testing using a locally build version of the library
- [ ] Update E2E tests to use the local library versus the released version the docker container uses by default.
- [ ] Delete the `Dockerfile` in the synthetics repo

We've always used a pre-release version of heartbeat for synthetics, so a SNAPSHOT build should be fine

**Comment by andrewvc** [comment]
Hmmm, I'm noticing some issues with the docker image that was actually built, so let's pause here till those are resolved. Specifically, I'm seeing `npm` not being available for some reason

**Comment by paulb-elastic** [comment]
This is done and Synthetics is part of the regular Heartbeat docker image now
