### ISSUE TITLE
exit with non-zero code when any step fails 

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#191]
+ Right now, we always exit the process with `0` even when there are step that contains failures. 

```
journey('test', async ({ page }) => {
  step('error step', async () => {
    throw new Error('boom');
  });
});
```

We already capture and show this error on both of our reporters, but we have to exit with non-zero code when `result.status == 'failed'`

**Comment by paulb-elastic** [comment]
As well as this update being mandatory for being able to use our CLI as part of a CI pipeline, this will also change the exit code, so adding this as a beta requirement.
