### ISSUE TITLE
Support extra HTTP headers for pages

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#198]
We should allow people to set custom headers, which must be done when initializing the page (via playwright's `extraHTTPHeaders` option on the page constructor). I propose we add this ability to `before` hooks, letting them either invoke a special method to set this, or set a special variable. This issue is a stub and could use more detail.

**Comment by paulb-elastic** [comment]
Just to comment that whilst we might want a neater interface for doing this (maybe as part of Fleet), a user can do this today if they need to, for example:
![image](https://user-images.githubusercontent.com/70908889/106598721-0922d980-6550-11eb-943d-5996d4b996d1.png)
