### ISSUE TITLE
Allow users to record journeys using playwright recorder

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#208]
+ Extend playwright recorder to output journeys that can improve the on boarding of new users. 
+ Extend the CLI to support new command `record, codegen` or something similar. 
+ Merge each action in the recorder to step to checkpoint each flow
+ Internally handle the browser/page closing as its done for the runner

**Comment by paulb-elastic** [comment]
Linking this to the [spike](https://github.com/elastic/uptime/issues/295) to look at recorder options

**Comment by andrewvc** [comment]
Closing for now since we're currently building our own recorder.
