### ISSUE TITLE
Investigate network usage from Synthetic runs in GCP

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#217]
Analyse the download and upload traffic during Synthetic runs in GCP to determine what causes it, and if the rates seem acceptable compared with the size of the site(s) being tested.

**Comment by vigneshshanmugam** [comment]
@paulb-elastic can we close this issue as we already figured out the problem offline?

**Comment by paulb-elastic** [comment]
I’ve been running two GCP instances of Synthetics for the last couple of weeks.  Each is running 15 Synthetic monitors at 20 minute frequencies (the local todos app is also running, but I am ignoring those as they run from the local file system).

I haven’t seen any high network upload or download levels during that time:

Europe West 2C instance:

![image](https://user-images.githubusercontent.com/70908889/112183972-acaa7500-8bf6-11eb-8bcb-8cf485b638a0.png)

Europe West 4A instance:

![image](https://user-images.githubusercontent.com/70908889/112184045-bdf38180-8bf6-11eb-9894-9dfb5ae2ba33.png)
