### ISSUE TITLE
Record `dataLength` from Chrome Dev Tools Protocol

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/synthetics#220]
Currently, we record `encodedDataLength` from Chrome Dev Tools Protocol, but not `dataLength`. It would be helpful to have both values to display to the end user as part of the waterfall chart flyout.

Associated ticket: https://github.com/elastic/kibana/issues/80166

Reference: https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-dataReceived

**Comment by vigneshshanmugam** [comment]
Can you also add how we are planning to use these values in the UI or associated ticket.

**Comment by dominiqueclarke** [comment]
Updated above.

**Comment by paulb-elastic** [comment]
For reference, the UI issue for this is https://github.com/elastic/kibana/issues/94741
