### ISSUE TITLE
RUM agent transactions triggered by synthetics browser script don't register with APM

### ISSUE THREAD

**Issue by michaelhyatt** [elastic/synthetics#223]
I can see the Uptime monitoring registering synthetics monitoring scripts, but APM doesn't register any of the RUM transactions that synthetics browser should produce. I tried adding `setTimeout()` to the playwright scripts thinking that the synthetics browser shuts down before it is able to send the RUM traces, but it didn't help.

How to reproduce:
I am using scripts and the whole setup is available as docker-compose bundle. To run, do `TAG=7.11.0 docker-compose up` in a directory where the archive is unzipped. Let it run for a while and see that only the transactions for the Java backend appear in APM with no RUM transactions and traces.

[apm_lab.zip](https://github.com/elastic/synthetics/files/5994023/apm_lab.zip)

**Comment by vigneshshanmugam** [comment]
The timeouts wont help here as it cannot control once your navigation has been successful. What could help here is waiting specifically for that particular request. For the RUM agent we know the intake API request is going to be of this form `/intake/version/rum/events`. So we could wait for that particulat request in our journey suite

```ts
import { journey, step } from '@elastic/synthetics';

journey('testing rum', async ({ page }) => {
  step('wait for intake api', async () => {
    await page.route(/intake/, async a => {
      const request = a.request();
      console.log('URL', request.url());
      console.log('Data', request.postData());
    });
    await page.goto('https://elastic.co');
    await page.waitForRequest(/intake/);
  });
});

```

Let me know if that helps.

**Comment by michaelhyatt** [comment]
Do I need to have both, `await page.route` before and `await page.waitForRequest` after for the RUM events to sync?

**Comment by vigneshshanmugam** [comment]
No just `await page.waitForRequest` should do it. I just demonstrated what you can do with listening for that request. Hope it helps.

**Comment by michaelhyatt** [comment]
Added this to my step, still no luck with RUM transactions in the APM UI:
```typescript
    step("load homepage", async () => {
        await page.goto('http://petclinic:8080/');
        await page.waitForRequest('http://localhost:8200/intake/v2/rum/events');
    });
```

**Comment by vigneshshanmugam** [comment]
Can you change your script and check if you can see the console log message logged. 
```
    step('load homepage', async () => {
      await page.route(/intake/, async a => {
        const request = a.request();
        console.log('URL', request.url());
      });
      await page.goto('http://petclinic:8080/');
      await page.waitForRequest(/intake/);
    });

```

**Comment by michaelhyatt** [comment]
I am getting this line logged:
```
heartbeat-synthetics    | 2021-02-24T09:04:03.811Z	INFsynthexec/synthexec.go:271	stdout: URL http://localhost:8200/intake/v2/rum/events
```

**Comment by michaelhyatt** [comment]
Got it to work with only `await page.waitForRequest(/intake/);`. I was running it in docker-compose and switched to use the `network_mode: host` to fully mimic how the local browser is initialising the RUM agent, i.e. with localhost:8200/intake.

All is well, just adding the `waitForRequest()` solves it.
