### ISSUE TITLE
capture unhandled exception on tested pages

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#226]
+ we only capture JS errors console error and warnings which are captured via `console.error` and `console.warn`.

+ Need to capture uncaught exceptions that gets thrown which would be useful for debugging and associate it with each steps. 

We can use `page.on('pageerror')`  events - https://playwright.dev/docs/api/class-page/#pageonpageerror

**Comment by dominiqueclarke** [comment]
Seeing this implemented all the way through to Kibana for Synthetics agent `beta.16`, when tested against Kibana branch 7.16 and commit `0c347055e667851383a7415dfeaaa985bc01fe07`
<img width="1501" alt="Screen Shot 2021-11-01 at 4 27 12 PM" src="https://user-images.githubusercontent.com/11356435/139738056-b2a749ea-7111-4bf5-a85f-e30767a3a2a2.png">
