### ISSUE TITLE
Elastic Synthetic Identifier In UA String

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#232]
As a Synthetics user
I want to be able to easily identify Elastic Synthetic traffic in my analytics
So that I can exclude such traffic from my visitor volumes as this monitoring skews real customer figures

ACs:
* The user agent string should include some kind of addition to identify monitors running from Elastic Synthetics (appending `Elastic/Synthetics` to the actual UA string)
* It must still be possible to identify the actual browser making the requests (i.e. it won't remove or overwrite the *natural* UA string completely)
* There must be a configuration parameter (boolean) associated with the monitor to control this behaviour, defaulted to enabled (needed for the rare cases where a non standard UA string may cause problems with UA sniffing)

Referencing somewhat related tickets:
* https://github.com/elastic/synthetics/issues/151
* https://github.com/elastic/uptime/issues/302

**Comment by dominiqueclarke** [comment]
Seeing `Elastic/Synthetics` appended in the user agent when run in headful mode on version `beta-16`. 

<img width="1281" alt="Screen Shot 2021-11-01 at 4 10 08 PM" src="https://user-images.githubusercontent.com/11356435/139735523-41e4db82-2fa8-4a45-8847-3534e4df76e6.png">
