### ISSUE TITLE
Add option for JPEG screenshots

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#233]
For those who are space conscious JPEG screenshots would be welcome as a CLI option. We would need to add a corresponding heartbeat option.

**Comment by vigneshshanmugam** [comment]
Why don't we default to jpeg? Any objection to that using it on the Uptime UI vs the current png type?

**Comment by andrewvc** [comment]
@paulb-elastic raised the point that visual diffs, if we choose to use them in the future, don't tend to work as well with jpeg. I'd be inclined to just switch to jpeg for now however, and move to PNG later if we can find value there.

**Comment by vigneshshanmugam** [comment]
Yeah i get the visual diff behaviour, but we are not there yet and if we right now aim for the storage space, then jpeg with quality 80 default would be the right choice and would work great for both thumbnail and our full picture in the Uptime UI.

**Comment by paulb-elastic** [comment]
I’m ok changing this to be the default.  Will there be any changes needed to Uptime to support the different format?

Similarly, I would suggest Uptime needs to be able to automatically handle PNG and/or JPEG automatically, for if we do add a PNG option to Synthetics in the future for higher fidelity screenshots for features like visual comparisons.

**Comment by andrewvc** [comment]
@paulb-elastic let's do a local change and test it, IIRC we didn't hard code the MIME type, and send it with each request, so we should be good.

**Comment by shahidmgr** [comment]
@andrewvc do we updated the JPEG code officially? or any option to do in configuration files?
