### ISSUE TITLE
Add support for injecting APM trace details for every run

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#245]
+ Having the ability to propagate the trace details of each run would allow users to match each suite in the Uptime and APM UI. 
+ Heartbeat side is covered here - https://github.com/elastic/uptime/issues/302

**Comment by graphaelli** [comment]
Expanding on this description a bit, I'm hoping we could start with detecting whether the Elastic APM RUM agent has instrumented the target and include trace id(s) associated with a synthetic step in their run results, to allow insight into where time was spent serving the synthetic check.

**Comment by paulb-elastic** [comment]
@vigneshshanmugam is this the same as https://github.com/elastic/synthetics/issues/265

**Comment by vigneshshanmugam** [comment]
@paulb-elastic Yes, we can close this one in favor of #265
