### ISSUE TITLE
DNS failures not represented correctly

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#246]
There was a [suggestion](https://github.com/elastic/synthetics/issues/175#issuecomment-755012081) that this may have been fixed, however we still don’t appear to correctly represent DNS failures in the waterfall chart.

There are two different cases of where the failure can occur, and each behaves slightly differently:
* Where the root request fails (e.g. `await page.goto("http://www.thisisaninvaliddomain.com")`), this shows nothing in the waterfall chart
![image](https://user-images.githubusercontent.com/70908889/112473901-d7b3d680-8d66-11eb-91f3-0933856f92be.png)
* Where a non root network request results in a DNS failure, in which case we show a row/entry on the waterfall chart, but don’t show any DNS timing data for it (i.e. how long it took for the DNS lookup to take place, and fail)
![image](https://user-images.githubusercontent.com/70908889/112474590-bc959680-8d67-11eb-9348-4153a924a137.png)

**Comment by vigneshshanmugam** [comment]
@paulb-elastic Can you share the snippets that you used for testing both scenarios?
