### ISSUE TITLE
Capture filmstrip images

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#250]
This is the Synthetic Agent requirement to capture filmstrip images to be able to deliver the user story feature in https://github.com/elastic/kibana/issues/83816 (refer to it for the requirements).

Synthetic (real browser) monitors should capture filmstrip images for all steps of a user journey.  This was [changed](https://github.com/elastic/synthetics/issues/143) to be controlled by a flag (default to off).  It may be simply a requirement of passing the correct flag, however, we need to understand if there is a limit to 450 *frames* captured based on the [Chrome implementation](https://source.chromium.org/chromium/chromium/src/+/master:content/browser/devtools/devtools_frame_trace_recorder.h;drc=8a7a011299b9d7c375b0974249d941e06dfc48bf;l=31), and discuss this limitation.

**Comment by vigneshshanmugam** [comment]
This is pretty much done from the Synthetics agent perspective. One thing we do in the agent is to eliminating excessive screenshots currently defaulting to 2 frames per second, This aligns with Lighthouse and mostly for our own storage concerns. 

For our elastic.co journey
#### Excessive Filtering ON

```
   1 "synthetics/metadata"
   1 "journey/start"
   2 "step/end"
 146 "journey/filmstrips"
   1 "journey/end"
```

#### Excessive Filtering OFF
```
   1 "synthetics/metadata"
   1 "journey/start"
   2 "step/end"
  10 "journey/filmstrips"
   1 "journey/end"
```

**Comment by paulb-elastic** [comment]
@vigneshshanmugam I assume this still has the 450 Chromium limit, but with a 2 per second configuration, means we'll get a filmstrip of the first 225 seconds of a user journey?

**Comment by vigneshshanmugam** [comment]
@paulb-elastic Yes thats correct, I haven't really tested them in practise. But we can try it out if we want to support a journey that runs more than 4 minutes (approx).

**Comment by vigneshshanmugam** [comment]
Closing this issue as its done. With the recent changes on our tracer https://github.com/elastic/synthetics/pull/369 , the `450` limits without excessing filtering for images has changed from `Journey` level to `Step` level which gives enough room for the UI to accommodate them.
