### ISSUE TITLE
Journey callbacks shouldn't be async

### ISSUE THREAD

**Issue by spalger** [elastic/synthetics#256]
`journey()` callbacks are currently forced to be async by the types, but best I can tell we shouldn't be doing any async work in those callbacks, right? All async work should be wrapped in a `step()` and then executed by synthetics. I think that would be more obvious if the types required a `void` return type for the callback.

**Comment by vigneshshanmugam** [comment]
Indeed it shouldn't be `async`, we forgot to cleanup while doing the syntax change.
