### ISSUE TITLE
Spike: Reduce disk usage of screenshots / network data

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#266]
We currently use more disk space than desired to store synthetics screenshots this issue serves to track our efforts to reduce the total amount of disk space.

We have a number of thoughts on how to improve this:

### Lifecycle by status

We currently store the following datasets, `browser`, `browser_network` and `browser_screenshot`. We could migrate to `browser`, `browser_network_{up|down}`, and `browser_screenshot_{up|down}`. With this strategy segmenting indices by result status users could etablish a separate data lifecycle for failures vs. successes. Most users we've talked to would prefer to keep failures around longer than successes. Note that the core `browser` dataset does not have in the example listed above a namespace by up and down status. The rationale for not doing that is that it might be nice to depend on the lightweight core metadata existing and mostly focus on life cycle for the much more resource intensive network data and screenshot use cases.

This approach would require that we buffer the Elasticsearch documents from the run on the box running the synthetics tests. the reason we would need to do this is that we don't know whether the run is a success or failure until it is complete. We could simply do this with temp files on the system.

### Sampled Screenshots

We could add an option to only index successful runs a certain percentage of the time, in a way that is somewhat reminiscent to APM sampling.  Since users mostly care about failures, we would only store the core metadata for each run on most synthetics executions, say only one in 10 runs. Since most of the storage space is taken up by screenshots and network data this would result in a tenfold reduction in storage costs for monitors and mostly succeed. We would make sure to always store data for the run on any state change in other words if it had gone from a success to a failure we would store the first failure event in full.

One challenge with this approach is that we would need UI support for it to make sense, users would need to have a different experience when viewing a sampled run versus Hey fully hydrated run with all screenshots. We could point them at the most recent run with full screenshots if they wanted to see the screenshots.

### Screenshot diffs

Another approach would be to steal from the world of video encoding. Most video codecs work by coding a mixture of keyframes and I-frames (intra frames). A keyframe is a full image, an I-frame is a much smaller set of pixels that changed since the last keyframe. We would not need to use an actual video codec for this, but rather could simply only encode keyframe images for a given step every once in awhile and use a simple diff algorithm to store the different pixels on subsequent runs as a PNG.  A downside of this approach is that we would need to use some custom logic to layer the diff pixels on top of the keyframe. Additionally the synthetic's runner or heartbeat would need to retain the last keyframe and do the diff. It would make more sense for heartbeat to manage the retention of the last keyframe, potentially querying Elasticsearch to retrieve it.

**Comment by andrewvc** [comment]
After a discussion with @vigneshshanmugam we've agreed to tackle this on three fronts:

## De-duplication in ES across journey runs

We can use the fingerprint processor to de-duplicate fully identical screenshots

Process:
* Hash the raw image data
* Write a new synthetics/shared_screenshot object using the hash as the ID and the image data as a blob
* Write the current synthetics/screenshot object which is now a pointer to the shared screenshot, with no image data itself
* Always write a new shared screenshot every schedule_interval

Heartbeat pseudo-code

```
foreach json_line from synthetics_cli {
  if json_line is screenshot {
    screenshot_hash = hashof(screenshot.image_data)
   # See _create https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#docs-index-api-desc
    write_to_es(synthetics.type=shared_screenshot, es_doc_id=screenshot_hash, _create) 
    write_to_es(synthetics.type=screenshot, screenshot_type=pointer, points_to=screenshot_hash)
  }
}
```

## Image diffs between steps

* We can use a Keyframe / I-Frame approach to only encode what changed between steps in a given journey run. PNGs with transparency should encode efficiently.

**Comment by paulb-elastic** [comment]
I'm assuming we're using the `schedule_interval` to ensure there's always a screenshot for newer tests (in cases for example where a screenshot from `now` is identical to another from a while ago, which may be aged by an ILM policy)?

What might we consider that to be, something like 1 day?

**Comment by vigneshshanmugam** [comment]
After having some discussions asynchronously about the screenshots and storage reduction. For now, I am leaning towards easy wins like capturing screenshots only when a step has failed or error journeys (when journey fails for some reason - might be tricky as we need to post process a lot of things). This is same as the proposal here - #73.

we can come back and iterate on the idea by taking advantage of deduplication/compression feature in ES before GA. The approach is discussed here - https://github.com/elastic/synthetics/issues/266#issuecomment-840782985

Thoughts @drewpost @paulb-elastic ?

**Comment by drewpost** [comment]
Thanks for the through work on this. I love the end goals of cleverly using de-duping to help users solve this problem. That being said, depending on the type of site, that may not be enough. (imagine sites with lots of dynamic content. We'd also need to do it per testing node location as there would be potentially different content like ads etc per region). In the spirit of incremental improvement, though, I'm ok with a simpler solution that addresses the issue of their impact on storage. 

A couple of questions from me:

- Is this an optional setting for users? (ie can they choose to capture all?)
- What would the default value be?
- Given the main driver of this is cost savings, could we not keep all screenshots but then drop screenshots after a period of two weeks from storage.

The thing I have an issue with is that screenshots are really valuable tools. @paulb-elastic can attest to this from Eggplant as well. The value vs cost was significant. Screenshots lose value as they age though so I would prefer we approached it more from an ageing out scenario that just only capturing them on fails.

**Comment by paulb-elastic** [comment]
We have https://github.com/elastic/beats/issues/25201 for the initial (simpler) implementation, and I'd agree, we should incrementally enhance the efficiency with more complex solutions.

Depending on the complexity of the buffering issue in https://github.com/elastic/beats/issues/25201, it would be ideal if it's controlled at the user journey level (i.e. a failure in any step, stores the screenshots of all steps, when set to `on_error`).

I think we have to weigh up if it's worth adding the difference indices for types of screenshots (like Andrew's `browser_screenshot_{up|down}` idea), or if de-duping is a better option.  I know from previous similar systems that de-duping had a considerable saving.  Combined with a "delete screenshots older than *n* days" ILM policy should also give flexibility to the user.  On reflection, I am wondering if having separate indices for `up` and `down` (along with their associated ILM policies) does push too much complexity to the user (again, assuming we have a de-dupe solution in the medium term).

/cc @jahtalab who is working on https://github.com/elastic/beats/issues/25201

**Comment by drewpost** [comment]
> On reflection, I am wondering if having separate indices for `up` and `down` (along with their associated ILM policies) does push too much complexity to the user (again, assuming we have a de-dupe solution in the medium term).

Why can't we just manage that via UI controls in settings? Do we have to expose the mechanics of what's happening in the background?

**Comment by paulb-elastic** [comment]
I agree (we can simplify via UI), I just wondered if this additional level of complexity was needed if we have de-dupe (which I think we need in the longer term).

**Comment by andrewvc** [comment]
Having evaluated a number of options, de-duplication seems most promising, with an experiment proceeding here: https://github.com/elastic/synthetics/issues/266

**Comment by andrewvc** [comment]
Closing in favor of our initial approach here: https://github.com/elastic/synthetics/issues/285
