### ISSUE TITLE
[Proposal] allow configuration through `synthetics.config.js`

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#270]
+ Suite params options is super useful for passing down params for every journey files, however it becomes difficult when there are multiple environments involved like `staging`, `ci` and `production` and the whole suite level params keep changing for each of those environments. The proposal address that by allowing a configuration file which lets users inject params depending on the environment. 

```js
module.exports = {
  // defaults to development
  params: {
    url: 'http://localhost:8080',
  },
};

// To change params based on environment, users can return
// a function

module.exports = env => {
  if (env === 'development') {
    return {
      params: {
        url: 'http://localhost:8080',
      },
    };
  }
  return {
    params: {
      url: 'http://elastic.co',
    },
  };
};
```

**Note: params is explicitly kept as key to allow extending this configuration in the future.**

This setup and validation of config would be done before invoking any journeys and we would pass down these parameters to the individual journeys. 

```js
beforeAll(({ params }) => {
  let server;
  if (params.env === "development") {
    server = await startServer();
  }
});

afterAll(({ params }) => {
  if (params.env === "development") {
    server.stop()
  }
})

journey('journey1', ({ page, params }) => {
  step('step1', async () => {
    await page.goto(params.url);
  });
});

```

Purposefully this model exists as we don't want to support any other way of loading configs, By that I mean we don't want to support `.json`, `.yml` or any other extensions. Let's stick to a single way of doing config loading.

**Comment by andrewvc** [comment]
I love this proposal except one question: why make the user write conditional logic to determine which programs to return for which environment? What if we just had an object that was keyed by environment name so they didn't have to write the else logic? Development would be the default environment.

I'm open to this approach but I just like to hear your thoughts on this method versus the one I mentioned above.

**Comment by andrewvc** [comment]
Actually, I'm fine with the proposal as-is, no need to nitpick

**Comment by vigneshshanmugam** [comment]
I thought about that approach and went away from it due to two reasons

1. As we allow users to already to configure environment using -e flag, it felt more natural to pass down that config, instead of asking users to manually bookkeep it, Assuming users are invoking this script in `package.json`
```
"scripts": {
    "test:synthetics": "npx @elastic/synthetics -e 'staging' --config test/synthetics.config.js"
}
```
Users have to somehow sync the -e flag with the params, passing down the environment felt like a natural choice here. 

2. Small nitpick: Functions felt more composable and extendable than the plain JSON object.

**Comment by paulb-elastic** [comment]
This looks like a good option to me
