### ISSUE TITLE
propagate errors from `beforeAll` and `afterAll` hooks

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#280]
+ Now error in the `beforeAll` and `afterAll` hooks would be captured and reported as error, but they will not be associated with the reporters in the correct way. 
+ Without associating these errors, the Uptime UI will have no information about what happened during the context of a single execution. 

We have to figure out a way to solve this problem.

**Comment by andrewvc** [comment]
After discussion we should:

For `beforeAll`
1. Catch all errors in `beforeAll` and hooks
2. Emit `journey/start` and `journey/end` events for all journeys, with the error message + stack trace set as the error in the JSON

For `afterAll` we will continue with our current behavior for now, simply logging them in heartbeat
