### ISSUE TITLE
Sensible defaults for network throttling

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#284]
Although the more rounded solution for network throttling is defined in https://github.com/elastic/synthetics/issues/210, this is to at least provide sensible defaults for all monitors.

As a Synthetic user
I want all monitors to run with a sensible network throttling configuration
So that they don’t run at line speed and result in variable performance metrics based on how busy the network is

ACs:
* Determine a reasonable default network speed (upload speed, download speed and latency)
* Apply these to all monitors that run in Synthetics (inline, suites, `heartbeat.yml`, Fleet Integration)
* It is possible to override these defaults for specific monitors (e.g. via the script as shown in https://github.com/elastic/synthetics/issues/210#issuecomment-790502321)

Heartbeat issue here: https://github.com/elastic/beats/issues/27952

**Comment by paulb-elastic** [comment]
Discussed in refinement, and suggested defaults as:
* download: 5mbps
* upload: 3mbps
* latency: 20ms

**Comment by dominiqueclarke** [comment]
Will override options be exposed as heartbeat parameters at any point @andrewvc

**Comment by vigneshshanmugam** [comment]
In addition to having defaults, We need to have a add a CLI arg to disable throttling. `--no-throttling` should disable the sensible default throttling and would use the available network bandwidth as it is now.

**Comment by shahzad31** [comment]
Post FF Testing,

i need some help testing, how can we know throttling is being applied?

for example i am running like this

 `cat examples/inline/short.js | npx @elastic/synthetics --inline --throttling 5d/3u/20l --no-headless`

So i was expecting in the chrome network tool, throttling will be applied

but it still showed no throttling

![image](https://user-images.githubusercontent.com/3505601/139645718-b556fd20-6825-412f-942b-747e8382755e.png)


cc @dominiqueclarke

**Comment by paulb-elastic** [comment]
You can visit a page or URL with a specific payload size (e.g. a large bitmap image can be good) and compare how long the download takes with different speeds, and also compare to the theoretical download duration based on size and speed.  Similarly with upload throttling, POSTing a payload of a particular size.

Latency may be harder, as I don’t think you’ll see the impact for example on a SYN/ACK (TCP connection time) with emulated latency in Chrome.

It’s a good point about seeing the settings in the devtools UI - not sure if we should expect these to show the settings.  That would be useful to confirm the throttling settings have been made.

**Comment by dominiqueclarke** [comment]
Per @vigneshshanmugam, the CDP session set through playwright and the CDP session in the dev tools are actually two different settings, and the devtools does not directly correlate to the CPD session anyway. 

@vigneshshanmugam Please clarify if I misquoted you. 

@shahzad31 your best best is tested via the recommended approach from Paul.

**Comment by vigneshshanmugam** [comment]
@dominiqueclarke ++.

@shahzad31 They are two different instances of CDP session, so the chrome UI would not have any clue on what settings have been applied on the given session in any way. 

Another way to test would be to check the Network information API on the throttled page https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation

**Comment by shahzad31** [comment]
So i am using CLI to test this feature

first i tried this command 

`cat examples/inline/short.js | npx @elastic/synthetics --inline --throttling 10d/3u/20l --no-headless`

in this browser i first tried NetworkConditions api,

![image](https://user-images.githubusercontent.com/3505601/139822905-000dbeb8-04e4-4495-83fa-93a260ed12e4.png)

i can see the downlink speed being applied

i also tried fast.com speed test and it reflect the relevant throttling being applied

![image](https://user-images.githubusercontent.com/3505601/139823062-84636582-eb05-470b-baff-d916d79f5e84.png)


another test case

`cat examples/inline/short.js | npx @elastic/synthetics --inline --throttling 5d/3u/20l --no-headless`

This was also reflected properly.

With --no-throttling flag,

it reflected my connection speed

![image](https://user-images.githubusercontent.com/3505601/139823372-1e76e066-4783-48b1-b64f-1b01df893744.png)


without any flag being passed to cli, it reflected defaults

`cat examples/inline/short.js | npx @elastic/synthetics --inline   --no-headless
`
![image](https://user-images.githubusercontent.com/3505601/139823565-40c3bd2b-4d78-49eb-a482-cb5ca1e201c2.png)

![image](https://user-images.githubusercontent.com/3505601/139823722-8bd8063c-14d6-401a-aa6f-bbaa85d0a555.png)
