### ISSUE TITLE
Document how to retain data ILM policies

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#286]
Now that we have separate ILM policies for each type of monitor (https://github.com/elastic/uptime/issues/462), monitors running through Elastic Agent that make use of datastreams (which includes the Synthetics Service, and self-managed nodes https://github.com/elastic/uptime/issues/441), we should document how users can customise these to suit their requirements (e.g longer or shorter retentions based on the kind of data).

Considerations:
* Where should the entry point be for this documentation?
  * Monitor Management is a temporary UI, so perhaps we should show how to configure these for PUSH or Synthetics UI based monitors, or those running from [self-managed nodes](https://github.com/elastic/uptime/issues/441)
  * The existing Synthetics Integration will be deprecated and removed, in favour of the [self-managed nodes](https://github.com/elastic/uptime/issues/441), so probably not worth documenting that workflow
  * Perhaps the existing ILM / policy docs are the best place to highlight this (with a link from the Synthetics docs)
* Docs should include some indication of how the different types of data for different monitor types have a different storage profile (e.g. we know that the network data can take up the most space, and then screenshots)

**Comment by paulb-elastic** [comment]
Lower priority than https://github.com/elastic/integrations/issues/2196

**Comment by paulb-elastic** [comment]
This should wait for https://github.com/elastic/uptime/issues/453 to be done, in case that identifies changes to the way we configure data streams to ILM policies.

**Comment by paulb-elastic** [comment]
Rather than the original Synthtics Integration, I think we should re-purpose this to do it based on the https://github.com/elastic/uptime/issues/462 implementation (for the Synthetics Service), and then also the _new_ integration we'll get with https://github.com/elastic/uptime/issues/441

**Comment by paulb-elastic** [comment]
Updated this issue description as discussed in the docs sync yesterday

**Comment by paulb-elastic** [comment]
Discussed with @dominiqueclarke about the placement and content, and she suggested
> I think the documentation should either restate the information from the fleet document with a focus on the synthetics data streams, or link to the fleet documentation.
