### ISSUE TITLE
Add `--rich-metadata` flag to enable all rich metrics

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#289]
We currently have a number of flags that are used by heartbeat in conjunction with the `– – json` output, such as `--screenshots` and `--network`. As we add new flags we are creating a compatibility issue between heartbeat and the synthetics agent. Newer versions of heartbeat must add additional flags to gain from their functionality, thus breaking compatibility with older suites using older versions of the synthetics agent which do not support that flag.

This issue proposes adding a new meta-tag `--rich-metrics` that can stably be used by heartbeat which turns on the relevant flags in the synthetics agent. An additional benefit here is that adding new flags to the synthetics agent won't require adding them to the beats code base.

**Comment by vigneshshanmugam** [comment]
++ to this approach, We need to investigate a bit on our CLI param and options on how we can make use of commander for these grouping. I feel like `--rich-events` makes more sense as we already discussed screenshot does not belong much in metrics.
