### ISSUE TITLE
Package synthetics suites

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#293]
## Proposal

This issue proposes this issue proposes adding a new `elastic-synthetics pack` command that would create a zip containing only the needed typescript files to run the journeys in the user's repo. It would not include the user's `package.json` file, and would in fact fail if the user was using extra libraries.

This would produce a minimal zip artifact of just the files needed to run the users tests on a synthetics container. It could be downloaded quickly and even shared among synthetics containers very efficiently. 

Additional, these files would include a `elastic-synthetics-manifest.json` metadata file indicating how many journeys were included within, as well as their names.

## Context

Currently, running a synthetic suite requires setting up a node project in the same way the user has set their development environment up with the same `package.json` etc.

This is fine in many situations but present some problems in others. One problem with the status quo here is that it requires us to run NPM install to make sure we have the same libraries that the user has. For most users this is irrelevant and can be particularly troublesome if the running synthetics behind a firewall. If a user is only using the synthetics library they would be fine just using the system version of it and skipping the NPM install step completely. This would reduce failure points and also just make things more efficient.

**Comment by vigneshshanmugam** [comment]
Superseeded by #470
