### ISSUE TITLE
Add step duration as an indexed field

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#302]
We currently index the step duration of the field on the payload object. Users cannot search this data or make custom kibana visualizations with it. It would be useful to make step timing charts not only in uptime, but also in kibana dashboards.

This issue proposes we create a new field `synthetics.step.duration.us` which measures the step execution time in milliseconds. We can use the `root_fields`  JSON to add this field.

I had discussed with @vigneshshanmugam the possibility of making a new field for journey durations as well, however the existing `monitor.duration.us` field covers this. I'd rather not introduce a second field with the same information in milliseconds at this point since that may be confusing.

**Comment by vigneshshanmugam** [comment]
@andrewvc To make use of the `monitor.duration.us`, Do you think we can send the timestamp field denoting the proper journey end time as opposed to when the JSON output `journey/end` is written which might get fluctuated?
