### ISSUE TITLE
Improve mapping for additional metrics

### ISSUE THREAD

**Issue by shahzad31** [elastic/synthetics#303]
For newly added metrics in https://github.com/elastic/synthetics/pull/194

If you want to build visualisation for example on LCP.

First you will have to do filter on `browser.experience.name` and then use value from `browser.experience.name` , so they metric type is stored as value instead of field. 

I think we should add each metric as new field. Since this will make querying es data easier.

**Comment by vigneshshanmugam** [comment]
Did you see these changes in Heartbeat where we added new mappings for metrics? - https://github.com/elastic/beats/pull/26140

Would that solve your use-case?

**Comment by vigneshshanmugam** [comment]
Had a offline discussion with Andrew, The current data was written with network waterfall in mind where we can have mark points that are relative to the page navigation. 

The current Data structure
```json
{"experience":{"name":"firstContentfulPaint","type":"mark","start":1260980.142211}}
```

This explains that FCP happened after the `start` time with relative to the step/start and the UI waterfall can show a thin line indicating when that event happened similar to Devtools. Also this data structure is really important for showcasing user timings which needs start and end timings to visualizing them in the waterfall. 

To make the dashboard part easier, we can add key-value pairs in addition to the existing metrics

```json
browser: {
  experience: {
    dcl: 900,
    load: 5000,
    cls: 0.12,
    fcp: 1200,
    lcp: 1500,
  },
},
```

These are absolute values in `ms` that measures the duration of all experience metrics with relative to the navigation start timings. 

/cc @paulb-elastic @drewpost 

However these timings would be relative to

**Comment by andrewvc** [comment]
@vigneshshanmugam I think we need to separate things more, it's weird that there's these numbers and also `name` and `start`.

Maybe we should have it be:

```
browser: {
  experience: {
    dcl: 900,
    load: 5000,
    cls: 0.12,
    fcp: 1200,
    lcp: 1500,
    extended: {
      name: "...",
      type: "...",
      start: "...",
    }
  },
}
```

WDYT? Maybe there's a better name than `extended`.

**Comment by vigneshshanmugam** [comment]
Had a discussion with @andrewvc, We are going with the format below

```
    "browser": {
      "experience": {
        "lcp": 12000, // duration from nav start
         "relative_trace":  {
           name: "largest contentful paint",
           type: "mark",
           start: "112312.21312" // relative to step/start for network waterfall
         }
      }
    },
    "browser": {
      "user_timing": {
        "relative_trace":  {
            name: "start-render",
            type: "mark",
            start: "12312311.213"
        }
      }
    },

```
