### ISSUE TITLE
Network flag not being recognized

### ISSUE THREAD

**Issue by picolloo** [elastic/synthetics#334]
I recently bumped to version beta.6 and now I'm receiving this error when running
 heartbeat:

```bash
heartbeat_1  | 2021-07-01T11:01:24.610Z INFO    browser/browser.go:39   Synthetic monitor detected! Please note synthetic monitors are an experimental unsupported feature!
heartbeat_1  | 2021-07-01T11:01:24.986Z INFO    synthexec/synthexec.go:128      Running command: /tmp/elastic-synthetics-391316926/node_modules/.bin/elastic-synthetics . --screenshots --json --network --outfd 3 in directory: '/tmp/elastic-synthetics-391316926'
heartbeat_1  | 2021-07-01T11:01:25.247Z INFO    synthexec/synthexec.go:224      stderr: error: unknown option '--network'
heartbeat_1  | 2021-07-01T11:01:25.250Z ERROR   synthexec/synthexec.go:172      Error waiting for command /tmp/elastic-synthetics-391316926/node_modules/.bin/elastic-synthetics . --screenshots --json --network --outfd 3: exit status 1
heartbeat_1  | 2021-07-01T11:01:25.250Z INFO    synthexec/synthexec.go:176      Command has completed(1): /tmp/elastic-synthetics-391316926/node_modules/.bin/elastic-synthetics . --screenshots --json --network --outfd 3
heartbeat_1  | 2021-07-01T11:01:25.250Z WARN    synthexec/synthexec.go:183      Error executing command '/tmp/elastic-synthetics-391316926/node_modules/.bin/elastic-synthetics . --screenshots --json --network --outfd 3': exit status 1
```

_Originally posted by @picolloo in https://github.com/elastic/synthetics/issues/332#issuecomment-872145333_

**Comment by vigneshshanmugam** [comment]
Thanks for raising the issue, even though I fixed the issue, Its recommended to be in the older versions of the Synthetics as it's still beta and things might break if you update to the latest version. 

These breaking changes wont happen once we move the Synthetics to the `GA` which will happen in the future. So for now, I recommended keeping the version of synthetics at `v1.0.0-beta.2` which matches with the version shipped along with heartbeat for running inline suites (where synthetics version cannot be controlled through package.json). 

We will also add the compatibility matrix section to the docs so users would find these information easily. 

Please do let us know if you need help.
