### ISSUE TITLE
Unable to hide passwords which I am using under scripts

### ISSUE THREAD

**Issue by shahidmgr** [elastic/synthetics#341]
Hi @vigneshshanmugam /Team,

Please suggest how to hide passwords on Uptime page. I am trying to use the secret keyword but not working.

Please suggest if I can pass the password in any path or any other option which can hide password otherwise production we can not use Uptime.

Regards,
Shahid

**Comment by vigneshshanmugam** [comment]
Hi @shahidmgr,

We have docs on using the secrets and params which would be live from 7.14 - But you can have a look at them here for now - https://www.elastic.co/guide/en/observability/master/synthetics-params-secrets.html#synthetics-secrets-sensitive

Let us know if you need any other help.

**Comment by vigneshshanmugam** [comment]
Closing this issue, Let us know if you need any further help.
