### ISSUE TITLE
Add Tests for `elastic-agent`  and fleet E2E

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#360]
We need E2E tests for the fleet synthetics integration based off the `complete` elastic agent image once https://github.com/elastic/beats/pull/27052 is merged. These should cover all 4 protocols (HTTP,TCP,ICMP,Browser)

We should also add tests to the fleet integration to ensure those work if possible. It may be too complex to orchestrate, but we should try.

Covered protocols
- [ ] Browser https://github.com/elastic/kibana/issues/109730
- [ ] ICMP
- [ ] TCP
- [ ] HTTP

Additionally:

- [ ] These tests should run against all active branches (e.g. 7.CURRENT, 7.x, master), this will require coordination with the robots team

**Comment by dominiqueclarke** [comment]
Closed in elastic/synthetics#393
