### ISSUE TITLE
Popup handling in Synthetic

### ISSUE THREAD

**Issue by shahidmgr** [elastic/synthetics#373]
Hi @vigneshshanmugam I want to handle Popup if any comes in any of the steps.

I am not sure when the popup will come in my recorded scripts. 

Suppose I have 5 steps, in any of the steps popup may come or may not. If popup triggers any of the fix steps then it is easy for me to handle.

I want something like

If (popup) 
then handle 
else 
complete my steps

If I am using page.waitForEvent("popup") suppose popup come then its working fine otherwise its simply waiting for event and timeout.

Regards,
Shahid

**Comment by vigneshshanmugam** [comment]
Have  you tried with explicitly with timing down the popup event as you are unsure when they will be opened in new window. You can do `waitForEvent("popup")` with a timeout. 
```
await page.click("button")
await page.waitForEvent("popup", {timeout: 1000});
// waits for 1000 seconds 
// or combine them in single await 
const [popup] = await Promise.all([
  page.waitForEvent('popup', { timeout: 1000})),
  page.click("button");
]);
```

**Comment by vigneshshanmugam** [comment]
> In this Application 6-10 steps we need to scripts but I am not sure when pop up will come. Pop up may come any of the steps or may not be also.

Do you have an example script that you can share, Would like to play around and provide an answer.

**Comment by shahidmgr** [comment]
Hi @vigneshshanmugam I have shared a sample script via email to you.

**Comment by vigneshshanmugam** [comment]
Closing this as we have have agreed to a solution offline.
