### ISSUE TITLE
Support Playwright options (e.g. to define HTTP proxies)

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#388]
Per [this forum post](https://discuss.elastic.co/t/synthetic-monitoring-using-proxy-servers/283389) it would desirable for synthetics to support HTTP proxy servers for testing from within intranets via a CLI flag and heartbeat option vs. a config file. Playwright supports this, so should we.

There are other configuration options to support too, so for the purposes of this implementation, we will add a generic option for setting the Playwright options, which can for example include the proxy details.

ACs:
* Add a `--playwrightOptions` optional flag to Synthetics CLI, the value of which will be passed in ‘as is’ as Playwright options

**Comment by dominiqueclarke** [comment]
A few questions:

1. Is the only way to currently specify playwright options using the `synthetics.config.js` file? 
2. Will these options likely need to be adjusted for local development vs production testing?

**Comment by andrewvc** [comment]
Yes on both counts! The config file isn't great for adjusting production configs, so there def needs to be a heartbeat/integration setting here. The question is whether we just add this option narrowly, or add a generic `--playwrightOptions` flag in synthetics/heartbeat. 

The big advantage of a specific flag is that it makes setting it more discoverable, you can just run `elastic-synthetics -h`, the downside is we have to do more work to add more settings in the future.

**Comment by vigneshshanmugam** [comment]
This is a very good use case and we definitely need a way to solve this. ++ on having it on both Config (which is possible already) and CLI args as pretty easier to do consume them in object format instead of adding a new flag for each browser or context specific API. 

So `--playwrightOptions `{"proxy": { "server": "http://proxy-url" } }` should do from the CLI standpoint

PW docs - https://playwright.dev/docs/network#http-proxy

**Comment by andrewvc** [comment]
OK, I'm a fan. Adding it to the refinement agenda

**Comment by paulb-elastic** [comment]
Discussed in refinement, and we will initially focus on a `--playwrightOptions` parameter (which can be used for a number of configurations (such as proxy), which can always be extracted into their own options at a later date).

Issue description/ACs updated accordingly.

**Comment by justinkambic** [comment]
Post-FF testing LGTM.

I tested this by configuring the browser to run in `headless: false` mode via cli, overwriting default/configured behavior.
