### ISSUE TITLE
Regarding PHI Data

### ISSUE THREAD

**Issue by shahidrazam** [elastic/synthetics#395]
Hi @vigneshshanmugam /Team,

How we are going to handle **PHI** data for our websites?

Please share the details, Hope in GA release it will handle automatically :)

Regards,
Shahid Raza

**Comment by vigneshshanmugam** [comment]
@shahidrazam Are you still looking for a way to handle the PH data? 

Does this work for you - https://www.elastic.co/guide/en/observability/current/synthetics-params-secrets.html

**Comment by vigneshshanmugam** [comment]
Let us know if you need more help. Closing.
