### ISSUE TITLE
rewrite screenshots blocks timestamp with creation time 

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#411]
+ Currently screenshot block `timestamp` is based on screenshot blob construction time instead of when the screenshot was taken. As a result, the screenshot timestamp would be greater than the journey/end timestamp which is not true. 

### Wrong order
```
-- step/end timestamp
-- journey/end timestamp

--- screenshot/block timestamp
--- screenshot/block timestamp

-- end timestamp
```

#### Correct order
```
-- screenshot/block timestamp
-- screenshot/block timestamp

-- step/end timestamp
-- journey/end timestamp
-- end timestamp
```

**Comment by paulb-elastic** [comment]
Assuming the screenshot construction takes *some* amount of time, won'y this cause the step to appear to take longer because we’re counting the compute time to generate the screenshot?

**Comment by vigneshshanmugam** [comment]
@paulb-elastic Screenshot block construction logic is unchanged and it happens only after all the steps have been completed, so it wont get accounted in to the step/end time nor the journey/end time which we fixed recently as customers are seeing increased journey duration. 

The idea here is to use the `timestamp` of when the screenshot taken vs when the screenshot was processed (converting to blocks). We are moving to former approach.

**Comment by paulb-elastic** [comment]
Thanks @vigneshshanmugam

**Comment by dominiqueclarke** [comment]
7.16 Uptime UI looks good with good with `beta.17`. Timestamps for `step/screenshot_ref` are lower than timestamps for `heartbeat/sumamry` docs.
