### ISSUE TITLE
Add journey.duration.us to the JSON spec

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#412]
+ To keep it consistent with step duration calculation, Synthetics should write `journey.duration.us` and get rid of `start` and `end ` values. 
+ We also need to add this to the heartbeat fields spec - https://github.com/elastic/beats/blob/b9ced47dba8bb55faa3b2b834fd6529d3c4d0919/heartbeat/_meta/fields.common.yml#L164
+ We will also need to add this to the Elastic Synthetics integration field spec

**Comment by andrewvc** [comment]
Closing as it isn't something we'll act on soon.
