### ISSUE TITLE
Add retries in the synthetics

### ISSUE THREAD

**Issue by shahzad31** [elastic/synthetics#416]
Since playwright/test and other runners like cypress allows retires for the failed journey to counter the flaky tests.
We should also add the ability to retry in the runner.

If the test fails it should retry for a given number of time.

it can be a global setting or we can allow per journey retries.

**Comment by paulb-elastic** [comment]
Agreed - I know @drewpost is working on this as a requirement around retest and statuses of test runs.

**Comment by andrewvc** [comment]
Closing in favor of https://github.com/elastic/synthetics/issues/792#issuecomment-1607849435
