### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#424]
Per the rest of our org's repos we should make this change.

@v1v what do we need to do CI-wise to do so?

**Comment by v1v** [comment]
> what do we need to do CI-wise to do so?

Search for any `master` references and then create a PR with the change. Change the default branch to main.
In addition, it's required to open a PR in the infra repo to change the `jjbb` references, and maybe also in the docs repo to change the branches, similar to -> https://github.com/elastic/docs/pull/2323

I'd say, if the first batch of changes work fine, then I'll proceed with another second batch of changes. So synthetics could be in the second batch or maybe in the third one.

There is no rush, though, if you agree we can move forward, I'm happy to give a go soon.

**Comment by paulb-elastic** [comment]
This has been done.  @v1v is there anything else to do here, or can we close this?
