### ISSUE TITLE
Should we move `typescript` to devDepencies?

### ISSUE THREAD

**Issue by afharo** [elastic/synthetics#425]
https://github.com/elastic/synthetics/blob/5ddb5c281276ef70084269f767a6002c6040dafa/package.json#L54

When installing the package in a project, it brings TS with it. IMO, it should be moved to the devDependencies. What do you think?

**Comment by vigneshshanmugam** [comment]
We need it as part of the dependencies as we transpile the files if users have pased in `.ts` files. https://github.com/elastic/synthetics/blob/5ddb5c281276ef70084269f767a6002c6040dafa/src/cli.ts#L150

**Comment by afharo** [comment]
understood! thanks for clarifying :)
