### ISSUE TITLE
Users should be able to run inline TypeScript Journeys

### ISSUE THREAD

**Issue by lucasfcosta** [elastic/synthetics#427]
# Summary

Currently, users cannot run `.ts` journeys inline, as the runner will not transpile the input from `stdin`.

This happens because the `source` which goes into a `Function` is the raw input from `stdin`.

https://github.com/lucasfcosta/synthetics/blob/5ddb5c281276ef70084269f767a6002c6040dafa/src/cli.ts#L56-L64

We could use the `typescript` compiler to transpile that input to plain JavaScript before feeding it into the Function and thus enable users to run TypeScript journeys.

## Other details

This issue was found while investigating https://github.com/elastic/synthetics/issues/407. In the PR which solves issue we also enabled users to read `.ts` configuration files, and consequently I believe we should allow users to run `.ts` journeys too.

**Comment by RichiCoder1** [comment]
Typescript can be a very heavy dependency unless you're explicitly interested in typechecking, so some other (easy to integrate) options are [esbuild](https://esbuild.github.io/) and [swc](https://swc.rs/) which both do _very fast_ ts transpilation in addition to some nice other things.

Edit: Though looking at it, ya'll already take a dep on `ts-node`.
