### ISSUE TITLE
Address synthetic flaky tests

### ISSUE THREAD

**Issue by devcorpio** [elastic/synthetics#430]
# Context

It has been detected several flaky tests and the goal of this issue is to make them more stable. 

The tests encountered so far are:

- **network › timings for aborted requests**. [Pipeline](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-429/detail/PR-429/1/pipeline/309)
- **CLI › TLS site with self-signed cert › succeeds succeeds with --ignore-https-errors**. [Pipeline](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-428/detail/PR-428/1/pipeline/)
- **CLI › screenshots with device emulation**. [Pipeline](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-428/detail/PR-428/2/pipeline/)

# Findings

@emilioalvap have done some findings:

"some of the unit tests for synthetics are relying on the cli pipe to emit message individually but under certains circumstances two or more can be passed in the same event, making the out not-Json-parseable"

**Comment by emilioalvap** [comment]
To provide more details on some of the flakiness that I found, locally it all came down to `CLIMock` class and the interaction with the spawned node process that executes `cli.js`:

```js
this.process.stdout.on('data', dataListener);
```

Some tests are relying on data recevied through the handler to be a JSON object, which would be the case if the output were to be 1:1 between processes:

```js
expect(JSON.parse(cli.output()).journey).toEqual(
```

Local tests have shown that this condition is not always met, where the chunk received from the `node` process corresponds to a) multiple JSON objects, or b) a chunk of a large JSON object (mainly [blobs](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-428/detail/PR-428/2/pipeline/)).

[This section of node docs](https://nodejs.org/api/process.html#a-note-on-process-io) might be relevant in this situation.

**Comment by paulb-elastic** [comment]
Moving to the 8.2 board
