### ISSUE TITLE
Enable 8.1.0-SNAPSHOT for CI again

### ISSUE THREAD

**Issue by devcorpio** [elastic/synthetics#432]
# Context

The synthetics[ E2E pipeline](https://apm-ci.elastic.co/job/apm-agent-rum/job/e2e-synthetics-mbp/job/master/63/console) was failing when executing tests for 8.1.0-SNAPSHOT due to an unhealthy container: `ERROR: for elastic-agent  Container "dada48cb7ab1" is unhealthy.`

The reason of this issue was visible in the logs of that container:

```Kibana Fleet setup failed: http POST request to http://kibana:5601/api/fleet/setup fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}```

Issue where the agent team is working on a fix:  https://github.com/elastic/beats/issues/29603

# What to do

Since we [disabled](https://github.com/elastic/synthetics/pull/433) 8.1.0 to avoid having the pipeline failing repeatedly. What we need to do is enable it again once the fix is ready.

**Comment by awahab07** [comment]
**Post FF Testing**

LGTM: The pipeline is consistently stable over the past CI runs. 

Last successful run of the time of writing https://apm-ci.elastic.co/job/apm-agent-rum/job/e2e-synthetics-mbp/job/master/80/
![image](https://user-images.githubusercontent.com/2748376/148808126-17c27b53-8470-40a9-b093-ce9b1260c50f.png)
