### ISSUE TITLE
Air gapped/offline mode doesn't work

### ISSUE THREAD

**Issue by mybyte** [elastic/synthetics#445]
When running heartbeat (7.16.3) with synthetics as shown in the [todos example ](https://github.com/elastic/synthetics/blob/main/examples/todos/), the module is broken.

Does one of two things:

- tries to overwrite binaries in `node_modules/.bin` and `node_modules/node_static/node_modules/.bin`
- still doesn't work ***if*** it does (possibly broken links??)

Here's a minimal example to reproduce the issue: https://github.com/mybyte/synthetics-airgapped-issue

**Comment by vigneshshanmugam** [comment]
We are deprecating Browser Zip url monitors and moving towards `Project Monitors` - https://www.elastic.co/guide/en/observability/current/synthetic-run-tests.html#synthetic-monitor-choose-project which would solve the offline mode as we bundle the journeys and would not fetch any external modules when running the Heartbeat image. 

This is available from 8.4 release -  You can check out this walkthrough if you need more details - https://discuss.elastic.co/t/synthetics-8-4-0-release-new-workflow-video-walkthrough/314712 , Please do let us know if you need more help or feedback in general.
