### ISSUE TITLE
Synthetics fail to start with `illegal instruction (core dumped)`

### ISSUE THREAD

**Issue by MSDev201** [elastic/synthetics#472]
Somehow the synthetics fail to execute / start when running it on my server. (On my local pc all works just fine)

I could solve my issue by downgrading the `sharp` package of `@elastic/synthetics` in the package.json like so:
```json
{
  "dependencies": {
    "@elastic/synthetics": "1.0.0-beta.22"
  },
  "overrides": {
    "@elastic/synthetics": {
      "sharp": "0.25.4"
    }
  }
}
```

When running without the override I get the following error:
```
heartbeat           | 2022-03-19T23:06:44.618Z	INFO	synthexec/synthexec.go:148	Running command: /tmp/elastic-synthetics-1341487469/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-1341487469/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-1341487469 --screenshots on --rich-events in directory: '/tmp/elastic-synthetics-1341487469'
heartbeat           | 2022-03-19T23:06:45.251Z	INFO	synthexec/synthexec.go:195	Command has completed(-1): /tmp/elastic-synthetics-1341487469/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-1341487469/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-1341487469 --screenshots on --rich-events
heartbeat           | 2022-03-19T23:06:45.251Z	WARN	synthexec/synthexec.go:202	Error executing command '/tmp/elastic-synthetics-1341487469/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-1341487469/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-1341487469 --screenshots on --rich-events' (-1): signal: illegal instruction (core dumped)
```

**Comment by vigneshshanmugam** [comment]
@MSDev201  Thanks for raising the issue, Could you give more details on the system info of your server? 

More details are on this issue - https://github.com/lovell/sharp/issues/2723

**Comment by MSDev201** [comment]
The Server has a AMD Phenom(tm) II X6 1055T Processor.
16 GB DDR3 ECC RAM
OS: Ubuntu 20.04.4 LTS (Focal Fossa)
Heartbeat is running in docker with the `docker.elastic.co/beats/heartbeat:7.16.1` image but execution of the synthetics also fails when just running `npx @elastic/synthetics ./` with the same error.

**Comment by vigneshshanmugam** [comment]
As stated in the sharp thread https://github.com/lovell/sharp/issues/2723#issuecomment-842956537, They have removed support for outdated CPU's and not planning to support them any longer. 

I don't think we would do prefer to do a custom installation for `libvps` in order to support the older CPU's. As the product is still in beta phase, We will not be able to prioritize this issue and request you to either pin the version of Synthetics library or Sharp library as you have done already.
