### ISSUE TITLE
Main branch CI tests failing

### ISSUE THREAD

**Issue by cachedout** [elastic/synthetics#480]
Hello,

It appears as if several tests are [consistently failing](https://apm-ci.elastic.co/job/apm-agent-rum/job/e2e-synthetics-mbp/job/main/) on the main branch of the E2E tests for this project.

Here are the tests which are failing:

[E2e test synthetics - http create an http monitor.create an http monitor](https://apm-ci.elastic.co/job/apm-agent-rum/job/e2e-synthetics-mbp/job/main/90/testReport/junit/(root)/E2e%20test%20synthetics%20-%20http%20create%20an%20http%20monitor/create_an_http_monitor/)
    [E2e test synthetics - tcp create an tcp monitor.create an tcp monitor](https://apm-ci.elastic.co/job/apm-agent-rum/job/e2e-synthetics-mbp/job/main/90/testReport/junit/(root)/E2e%20test%20synthetics%20-%20tcp%20create%20an%20tcp%20monitor/create_an_tcp_monitor/)
    [E2e test synthetics - browser create an browser monitor.create an browser monitor](https://apm-ci.elastic.co/job/apm-agent-rum/job/e2e-synthetics-mbp/job/main/90/testReport/junit/(root)/E2e%20test%20synthetics%20-%20browser%20create%20an%20browser%20monitor/create_an_browser_monitor/)
    [E2e test synthetics - browser - inline create an browser monitor.create an browser monitor](https://apm-ci.elastic.co/job/apm-agent-rum/job/e2e-synthetics-mbp/job/main/90/testReport/junit/(root)/E2e%20test%20synthetics%20-%20browser%20-%20inline%20create%20an%20browser%20monitor/create_an_browser_monitor/)

Could somebody please investigate these failures? They appear to have been failing since March 22. Thanks!

**Comment by paulb-elastic** [comment]
@cachedout this has been reportedly fixed in https://github.com/elastic/synthetics/pull/479 which has been merged - can this be closed now?

**Comment by cachedout** [comment]
@paulb-elastic Yep! Thanks!
