### ISSUE TITLE
Update PW to the latest version

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#484]
+  Synthetics needs to be updated to the latest version of Playwright
+ Decouple the Synthetics formatter and move it to the recorder for the time being - https://github.com/elastic/synthetics-recorder/issues/185
+ Fastest way to solve some of the issues that users are experiencing with core dumps - https://github.com/elastic/beats/issues/30426

**Comment by justinkambic** [comment]
Post-FF testing LGTM.

**Comment by vigneshshanmugam** [comment]
@justinkambic Just want to make sure we got this right, Did you build a local HB image and try to run some browser monitors with it?
