### ISSUE TITLE
Documentation/introduction link is dead

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/synthetics#496]
This link is dead:  https://www.elastic.co/guide/en/observability/current/synthetic-monitoring.html.    Found the dead link from both the README.md and from a Google Search for "Elastic Synthetics"

**Comment by paulb-elastic** [comment]
@PhaedrusTheGreek thanks for bringing to our attention.

@colleenmcginnis is this from some of the restructure - could a redirect be added so we don’t lose the Google searches?

If you can confirm the new location, we can ensure the README link is updated to the new location too.  Thanks.

**Comment by colleenmcginnis** [comment]
Temporary redirect is on its way: https://github.com/elastic/observability-docs/pull/1826

Permanent redirect coming soon: https://github.com/elastic/website-development/issues/9253

**Comment by paulb-elastic** [comment]
Thanks for sorting this so quickly @colleenmcginnis 

I've created https://github.com/elastic/synthetics/pull/497 to update the readme to the new location for your review

**Comment by paulb-elastic** [comment]
Thanks @colleenmcginnis, I'll close this one now
