### ISSUE TITLE
[Docs] [Examples] Document how to use synthetics against apps which require auth

### ISSUE THREAD

**Issue by lucasfcosta** [elastic/synthetics#501]
Recently, there have been a significant number of questions about how to use Synthetics against apps which require authentication (including MFA)

We should create some more docs on how to handle those cases, and, _more importantly_ **we should create a demo app against which synthetics authenticates**.

**Comment by vigneshshanmugam** [comment]
Partly ties in with https://github.com/elastic/observability-docs/issues/2049
