### ISSUE TITLE
Synthetics init fails because `templates` weren't included in distributable

### ISSUE THREAD

**Issue by lucasfcosta** [elastic/synthetics#509]
# Summary

Right now, the `synthetics init` command fails because the `templates` folder is lacking files. If you build the package locally it runs fine because the templates will be copied, but if you use `npx`, for example, you will see the following error:

```
Error: ENOENT: no such file or directory, open '/Users/lucasfcosta/.npm/_npx/XYZ/node_modules/@elastic/synthetics/templates/.gitignore'
```

# How to reproduce

1. Run `npx @elastic/synthetics init my-project`

**Comment by vigneshshanmugam** [comment]
Figured out the issue, .gitignore files are ignored by NPM by default. Will change the strategy here.

**Comment by emilioalvap** [comment]
PostFF LGTM.
