### ISSUE TITLE
source location for journey files has incorrect filepath

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#520]
+ To extract the source location information for journeys, we rely on source-map library to extract the fileName and other stack related information. But there was a bug in the library that did not handle the absolute file paths correctly when extracting that info which lead to incorrect fileName and resulted in push command getting failed. 

```
Error: Build failed with 1 error:
error: ENOENT: no such file or directory, open '/Users/vigneshh/elastic/synthetics/examples/todos/file:/Users/vigneshh/elastic/synthetics/examples/todos/basic.journey.ts'
    at failureErrorWithLog 
....
  errors: [
    {
      detail: [Error],
      location: null,
      notes: [Array],
      pluginName: 'esbuild-multiasset-plugin',
      text: "ENOENT: no such file or directory, open '/Users/vigneshh/elastic/synthetics/examples/todos/file:/Users/vigneshh/elastic/synthetics/examples/todos/basic.journey.ts'"
    }
  ],
  warnings: []
}
```

But there is a fix in the latest version that handles the file urls correctly and also has better ESM support - https://github.com/cspotcode/node-source-map-support/pull/38/

**Comment by shahzad31** [comment]
Push command works now without the error !!
