### ISSUE TITLE
Support for lightweight monitors via projects

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#542]
With project monitors we now let users manage browser based monitors easily from the CLI, but that story does not extend to lightweight monitors. This limits the utility of our overall solution since users need multiple workflows, when they ideally could use project monitors for everything if desired.

This issue proposes supporting the YAML format used in heartbeat's `monitor.d` directory with project monitors. These would act the same as browser based monitors, only their definitions would be YAML based and included in the source tree. An example is listed below.

```
- type: http 
  id: my-http-monitor
  name: Lightweight HTTP Monitor
  schedule: '@every 5s' 
  hosts: ["https://www.elastic.co"]
  # New keys for service listed below
  locations: ["us-west", "japan"]
```

## Why YAML?

- Users will need to migrate existing configs, this being the exact same format they already use makes migration a breeze. 
- Lightweight monitors are more frequently used by administrators who are more comfortable with YAML than JS/TS and Node. Asking users with those personas to use JS/TS may hinder adoption.
- Ease of implementation, should be a simple translation to the API

## Gotchas / Known issues

- The IDs are not exactly portable since project monitors include the space and journey in the monitor ID. We could add a special config key `preserve_exact_monitor_id: true|false` to handle this situation.
- We won't be able to support cron syntax, or, if we do, we should support the subset that is translatable to `@every` syntax (the regex `(\*(\/\d)? )(\*(\/\d)? )\* \* \*` should match and capture cron jobs meant to run every N minutes or every N hours.
- Running locally is something we'll need to determine in the future. I propose that we initially just validate these and allow them to be pushed. Later we can determine a strategy for running these locally. Perhaps the simplest answer would be to just invoke `docker run` in `run_once` mode. For now, we could just validate the syntax of these monitors locally and mark them in some sort of `skipped` status.

**Comment by dominiqueclarke** [comment]
Kibana api for projects does currently assume browser monitor type, so updates to the api would be necessary to parse the type appropriately.

**Comment by andrewvc** [comment]
See also: https://github.com/elastic/synthetics/issues/599 and https://github.com/elastic/kibana/issues/140864

**Comment by awahab07** [comment]
**Post FF Testing**

`init`'d a project using the latest build and tried the push command with one browser and one lightweight monitor and it behaved as expected.

1. Returns the error for unsupported fields. For the following yaml config:
    ```yaml
    - type: http
      ...
      check.response:
        status: [200]
        body:
          - Text
    ```
    it returns
    <img width="809" alt="image" src="https://user-images.githubusercontent.com/2748376/193106997-1ff85c61-7060-40c2-be4b-5079631b53ad.png">

2. For duplicate ids, it returns
   <img width="483" alt="image" src="https://user-images.githubusercontent.com/2748376/193107153-95a96ec7-5653-41c3-8e62-d8ba53a64d65.png">

3. When validation passes, it pushes the monitors as expected.

4. However, it always shows the following warning regardless of the `schedule` value.
   <img width="863" alt="image" src="https://user-images.githubusercontent.com/2748376/193107685-63a6a542-e7df-4f70-84a5-29f121aa1b86.png">

**Comment by vigneshshanmugam** [comment]
> However, it always shows the following warning regardless of the schedule value.

Yeah this is expected  - See https://github.com/elastic/synthetics/pull/612#discussion_r980347789
