### ISSUE TITLE
Automatically update test version for E2E tests in setup.sh

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#543]
In [setup.sh](https://github.com/elastic/synthetics/blob/main/__tests__/e2e/scripts/setup.sh) we must manually bump the heartbeat container version. This is error-prone and labor intensive. We should automatically test against the latest versions.

We can get the latest N release and versions with the following shell script:

```
DOCKER_PATH=docker.elastic.co/beats/heartbeat
LATEST_RELEASE_TAG=$(curl -s 'https://docker-api.elastic.co/v1/r/beats/heartbeat/?show_snapshots=false' | jq -r '.results[] | select(.name|test("^[0-9\\\\.]+-amd64$")).name
	' | head -n1)
LATEST_RELEASE_DOCKER_IMAGE=$DOCKER_PATH:$LATEST_RELEASE_TAG
LATEST_SNAPSHOT_TAG=$(curl -s 'https://docker-api.elastic.co/v1/r/beats/heartbeat/?show_snapshots=true' | jq -r '.results[] | select(.name|test("^[0-9\\\\.]+-SNAPSHOT-amd64")).name
  ' | head -n1)
LATEST_SNAPSHOT_DOCKER_IMAGE=$DOCKER_PATH:$LATSET_SNAPSHOT_TAG
```

**Comment by vigneshshanmugam** [comment]
We have a proper E2E tests that run against Integrations with different versions. The caveat is that it's run only at regular intervals and not on every PR. We can reuse the same and make it run against each PR to be able to capture the errors aganist set of versions defined here - https://github.com/elastic/synthetics/blob/main/__tests__/e2e/versions

**Comment by andrewvc** [comment]
Closing, we should delete these tests eventually. See https://github.com/elastic/synthetics/issues/591
