### ISSUE TITLE
push command api key error

### ISSUE THREAD

**Issue by riba2101** [elastic/synthetics#549]
Hi,

during push we are getting the following error in kibana:
```
Error: Missing mappings for saved objects types: 'uptime-synthetics-api-key'
```

im kinda at a loss why this is happening (i dont fond even the type in kibana)
the ELK stack is 8.3.1
the @elastic/syntehtics is beta.26 (tried also with 30)

is there some doc that ive missed?

BR

**Comment by dominiqueclarke** [comment]
Hi @riba2101.

Can you confirm what type of deployment you are using? Are you deployed with Elastic Cloud, Elastic Cloud Enterprise, Elastic Cloud on Kubernetes, or a self-managed deployment?

**Comment by riba2101** [comment]
hi,

its a self managed non fleat option

br

**Comment by shahzad31** [comment]
> hi,
> 
> its a self managed non fleat option
> 
> br

@riba2101 push command isn't supposed to work with self managed at the moment. Can you describe in detail, how are you trying to use push command with uptime?

**Comment by riba2101** [comment]
hey,

rly? didnt know that...the docs are super scares!

what is supposed to be used? except inline?,
since zip and source are bing deprecated.

that being sad i know source is not working, or rather even with a custom docker being executed, but nothing is reported - no errors, no nothing.

what and when can we expect something usable for self-managed clusters?

br

**Comment by shahzad31** [comment]
> hey,
> 
> rly? didnt know that...the docs are super scares!
> 
> what is supposed to be used? except inline?, since zip and source are bing deprecated.
> 
> that being sad i know source is not working, or rather even with a custom docker being executed, but nothing is reported - no errors, no nothing.
> 
> what and when can we expect something usable for self-managed clusters?
> 
> br

We are actively working on it. You will be reading more on this from us in hopefully couple of releases :)

**Comment by vigneshshanmugam** [comment]
Closing the issue as the next release 8.4, we are releasing support for Private Testing locations.
