### ISSUE TITLE
Discovery option for public locations

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#551]
As a user of Synthetic Project Monitors
I want to be able to determine the public locations I can use for running tests from (via the service)
So that I know what configuration to add to my scripts

ACs:
* A mechanism in Synthetics to get the locations from the command line (e.g. `npx @elastic/synthetics locations --list`)
* This will return a list of locations
  * Parsed from https://github.com/elastic/synthetics/blob/main/src/dsl/locations.ts (i.e. is based on what the current version of the Synthetics package installed, knows about)
  * It must be clear from the list, what string the user needs to include in `monitor.use.locations: []`

**Comment by lucasfcosta** [comment]
Just E2E tested this using the latest released version of synthetics.

As a note, the command doesn't include the `--list`. It actually only requires `@elastic/synthetics locations`.

Running that command using `npx` to get the latest package version from the registry I see, as expected, the output below:

```
➜ npx @elastic/synthetics locations
Available locations:
   * japan
   * india
   * singapore
   * australia_east
   * united_kingdom
   * germany
   * canada_east
   * brazil
   * us_east
   * us_west

Set default location for monitors via
  - Synthetics config file 'monitors.locations' | 'monitors.privateLocations' field
  - Monitor API 'monitor.use({ locations: ["japan"], privateLocations: ["custom-location"] }')
```
