### ISSUE TITLE
Support for private locations in synthetics agent

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#552]
With our work on [private locations](https://github.com/elastic/uptime/issues/441) we'll need to add support to the synthetics agent for these new locations. 

This means supporting a new `private_locations` setting in addition to the `locations` where relevant. This means:

1. In the `init` generated `config.ts`, and included as an option when selecting a default location (it could be at the bottom of the list)
2. In `config.ts`
3. In the DSL

**Comment by paulb-elastic** [comment]
@andrewvc do you mean that this should include a list of private locations when running `init` (as opposed to just mentioning the existance of a `private_locations` option)?

The reason I ask is that Synthetics currently parses https://github.com/elastic/synthetics/blob/main/src/dsl/locations.ts to list the locations available, i.e. it’s a static list from the version you’re running `init` from.  It doesn’t talk to Kibana to get the list.

Although this could be possible, that would mean the user would also have to provide the Kibana URL when running `init` (like they do when running `push`).

**Comment by dominiqueclarke** [comment]
> Although this could be possible, that would mean the user would also have to provide the Kibana URL when running init (like they do when running push).

We investigating an option where users can configure their list of private locations using the location id, without talking to Kibana for v1.

**Comment by andrewvc** [comment]
Closing in favor of https://github.com/elastic/synthetics/issues/557
