### ISSUE TITLE
Bundle standard TOTP generator

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#570]
It'd be useful to include a TOTP library such as https://github.com/yeojz/otplib for our users who need to authenticate via MFA.

**Comment by vigneshshanmugam** [comment]
Closed by https://github.com/elastic/synthetics/pull/580

**Comment by paulb-elastic** [comment]
https://github.com/elastic/synthetics/pull/580 allows for modules to be bundled in Project Monitors (as opposed to bundling a specific TOTP library)
