### ISSUE TITLE
add support to delete the entire project with push

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#581]
+ This would be fairly trivial to implement without adding in any extra options like `--delete` or `--delete project`. Instead when users tries to run push in a empty project, we could prompt users with the message `Pushing empty journeys might nuke the journeys associated with the project id`, If user agrees, we could proceed with pushing the empty monitors and Kibana would nuke the entire project.

**Comment by paulb-elastic** [comment]
I like the idea of this being an interactive feature only, as that's generally when one would be wanting to delete all monitors with `push`, when testing things out from the command line.

**Comment by shahzad31** [comment]
POST FF Testing looks good, Now we can delete all monitors via push command !!
