### ISSUE TITLE
Add `publicLocations` setting, deprecate `locations`

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#582]
Right now it's confusing articulating the difference between a public `location` and a `privateLocation`. We should just make this consistent and add `publicLocations` setting, deprecating `locations`, making it an alias for `publicLocations`.

This initially came up in https://github.com/elastic/observability-docs/pull/2075/files#r944092068 .

**Comment by paulb-elastic** [comment]
@andrewvc with us soon going GA, I feel we need to live with this.  Closing, but reopen if you feel we should still do this,
