### ISSUE TITLE
Error when pushing monitors from the CI environment

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#590]
+ Currently we rely on `project.json` internally during the initialization phase to be able to reuse the configuration when pushing monitors later once the synthetics project is set up. This works good on local dev machines, But wont work on the CI as we need the configurations like `url, project and space` to be able to push to Kibana.

Push should be idempotent when running from Dev machine and also on CI.

**Comment by emilioalvap** [comment]
PostFF LGTM.

Steps I've followed:
1. Initialized a new project with `npx @elastic/synthetics init`.
2. Filled the required fields.
3. Checked project id, url and space are stored in `synthetics.config.ts`:
```javascript
project: {
      id: 'postff',
      url: '<kibana url>',
      space: 'test',
    },
```

4. Pushed monitors and confirmed data is reflected in Kibana:
![image](https://user-images.githubusercontent.com/95703246/192816289-e057dfa2-e16d-4ba5-a142-2cc009126ee0.png)

5. Pushed with options in CLI and confirmed they take precedence:
```
 $: npx @elastic/synthetics push ... --id cli --url <different kibana url> --space default -- journeys

✔ Monitors were pushed under the 'postff' project. Are you sure you want to push them under the new 'cli' (note that this will duplicate the monitors, the old ones being orphaned) (y/N) · true
> preparing all monitors
> creating all monitors
> 1 monitor created successfully.
> 1 monitor created successfully.
> 1 monitor created successfully.
> deleting all stale monitors
✓ Pushed
```
![image](https://user-images.githubusercontent.com/95703246/192821236-7dcfb10d-617e-45d1-9bb0-505f82154907.png)

6. Checked `project.json` is no longer created:
```
$ stat .synthetics/project.json
stat: cannot stat '.synthetics/project.json': No such file or directory
```

7. Checked that `project.json` is ignored when no data is provided:
```
$ cat .synthetics/project.json
{
  "url": "url",
  "space": "default",
  "project": "test"
}

$: npx @elastic/synthetics push  journeys
Aborted. Invalid synthetics project settings.

Set project id via
  - CLI '--id <id>'
  - Config file 'project.id' field

Run 'npx @elastic/synthetics init' to create project with default settings.
```
