### ISSUE TITLE
Unable to delete last journey in Kibana via the "push" command 

### ISSUE THREAD

**Issue by Chillwind132** [elastic/synthetics#600]
Hi Team,

We encountered an issue with project monitors in elastic, where we are unable to delete the last journey from Kibana via the [npx @elastic/synthetics push] command. Steps to replicate:

1) Create a sample project with npx @elastic/synthetics init <name-of-project> command.
2) Delete all sample journey files except for "example.journey.ts".
3) Push to Kibana using npx @elastic/synthetics push.
4) Delete the last "example.journey.ts" journey file under the \journeys directory.
5) Try pushing to Kibana again using npx @elastic/synthetics push -> "No Monitors found" error.
6) The monitor remains in Kibana and we are unable to delete it.

How can we remove this last monitor from Kibana? The "push" command does not work and the delete button is also greyed out in Kibana.

Thank you,
Mike

**Comment by shahzad31** [comment]
Thank you for raising this. We are fixing this in the PR here https://github.com/elastic/synthetics/pull/598

**Comment by vigneshshanmugam** [comment]
Delete support has landed in the new release - https://github.com/elastic/synthetics/releases/tag/v1.0.0-beta.35

Let us know if you need have any feedback/questions.
