### ISSUE TITLE
journey did not finish executing, 0 steps ran when calling exported function.

### ISSUE THREAD

**Issue by Marchelune** [elastic/synthetics#652]
Hi there!

I'm trying to structure my synthetic tests project by extracting methods (API requests mostly) to dedicated TS files. The problem is that I often hit the issue where my tests run and pass locally (with `npm test`), but the version I push to ELK's Uptime app (our ELK cloud is running 8.4.3) does not run at all. The monitor appears in a `Failed` state, and when I go to the details, I see 

> There are no steps for this journey
This journey did not contain any steps.
The journey's check group is 3388a32c-642b-11ed-9db9-ce3a36e90cb7.
There is no further information to display.

Under the history section, in the error column, I can see the following:

```
journey did not finish executing, 0 steps ran: command '/tmp/elastic-synthetics-unzip-20303004/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-unzip-20303004/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-unzip-20303004 --playwright-options {"headless":true,"ignoreHTTPSErrors":false} --screenshots off --throttling {"download":5,"latency":20,"upload":3} --rich-events --match My Example Journey --params "{1 hidden params}"' exited unexpectedly with code: 1
```

I manage to create a primer with exactly what seems to cause this failure, using the [base template](https://github.com/elastic/synthetics/tree/main/templates), with the following files in the `journeys` directory:

```
example.journey.ts
foo.ts
get-foo.ts
```

With the following content:

```typescript
// foo.ts
export class Foo {
    private readonly bar: string;
}


// get-foo.ts
import { Foo } from './foo';

export function createFoo(): Foo {
    return new Foo();
}


// example.journey.ts
import { expect, journey, monitor, step } from '@elastic/synthetics';
import { createFoo } from './get-foo';

journey('Journey foo no params', ({ page, params }) => {
    // Only relevant for the push command to create
    // monitors in Kibana
    monitor.use({
        id: 'example-monitor',
        schedule: 10,
        screenshot: 'off',
    });

    step('getFoo()', async () => {
        const foo = createFoo();
        expect(foo).toBeDefined();
    });
});
```

Do you have any guidance on how to interpret `journey did not finish executing`?

Edit: removed unimportant `import` statement to reproduce the issue.

**Comment by Marchelune** [comment]
So I dug a little more into the problem, and I think the issue has something to do with the bundling process. I am not familiar with ESbuild, but it seems to me that in the sample given above, the JS module `foo.ts` is not bundled with the rest of the journey. It seems that only files directly referenced by the journey are bundled with it.

This works for me:

```typescript
import './foo.ts' // <--- forcing ESLint to see the reference and bundling the file
import { expect, journey, monitor, step } from '@elastic/synthetics';
import { createFoo } from './get-foo';

journey('Journey foo no params', ({ page, params }) => {
    // Only relevant for the push command to create
    // monitors in Kibana
    monitor.use({
        id: 'example-monitor',
        schedule: 10,
        screenshot: 'off',
    });

    step('getFoo()', async () => {
        const foo = createFoo();
        expect(foo).toBeDefined();
    });
});
```

Shouldn't the bundling configuration automatically bundle all referenced file, including "indirect" references?

**Comment by andrewvc** [comment]
Hmmm, to be clear here, it sounds like esbuild is only going one level deep, when it should recurse. Is that right? 

If so, yes it should do that, I think we simply don't have tests for that yet. Good find!!! Thanks for the clear comms here as well.

**Comment by Marchelune** [comment]
Thanks Andrew! Yes, I believe it should recurse.

**Comment by vigneshshanmugam** [comment]
Good catch, We were not following the links when the depth > 2, Will do a PR soon.
