### ISSUE TITLE
Runner doesn't follow playwrightoptions timeout value

### ISSUE THREAD

**Issue by shahzad31** [elastic/synthetics#662]
Synthetics runner browser context always use default timeout of 30 seconds, it doesn't follow the value specified in playwrightoptions.

**Comment by vigneshshanmugam** [comment]
Removing the bug label as it's not appropriate. 

Plus this needs to be solved in a different way given we diverse from the playwright timeout options - https://github.com/elastic/synthetics/issues/561#issuecomment-1215610563
