### ISSUE TITLE
Push is broken on main for old monitors !!

### ISSUE THREAD

**Issue by shahzad31** [elastic/synthetics#677]
Push few monitors using an older version of the agent  like `@elastic/synthetics": "^1.0.0-beta.39",`

Switch to main and try to push again, it will throw this error

<img width="778" alt="image" src="https://user-images.githubusercontent.com/3505601/206525548-ebdb89bf-4d4b-44bd-bf6d-070cb6551d10.png">

**Comment by vigneshshanmugam** [comment]
This is not a valid issue, To make it work with different versions, you would need to run with `npm run push`, Having a different version in the synthetics project and using it via different version for pushing will run in to consequences like this. Closing this as it is.
