### ISSUE TITLE
Prompt for overwriting files on existing scaffolded projects

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#680]
+ Running init multiple times might be necessary when we add new features like adding lightweight monitors or upgrading experience if we want to support new locations and so on.
+ The agent would allow users to override the files, but prompts on overwrite. This gets the clean state, plus also keeps the push command from not breaking if the user tries to run it after scaffolding a existing project.

**Comment by paulb-elastic** [comment]
Moving to Done Done, seen the prompt and ability to control what's updated with additional `init`s
![image](https://user-images.githubusercontent.com/70908889/213222644-ed0c8405-2cbb-4d5a-b931-ad4eb408e341.png)
