### ISSUE TITLE
Treat 'after' and 'before' code as a step

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#691]
It's currently not possible to debug failures in the 'after' and 'before' stages of a journey. After discussion with @dominiqueclarke , the best path for now is likely to generate an extra 'after' step in the output, and not to factor that into the calculation of the `journey/end` timestamp. 

While it might have been nicer to use an after-specific message type for this purpose, it would require significant UI work. Simply emitting an extra step is likely to only require a change in this repository, rather than across this, heartbeat, and the UI. In the future we can consider refactoring this. The steps UI in Kibana shows detailed browser network data and error information already, and so is ideal.

We would not emit these steps if no 'after' or 'before' hooks are registered.

**Comment by paulb-elastic** [comment]
Continuing to discuss (started in Tech Sync earlier today)

**Comment by paulb-elastic** [comment]
Discussed in Tech Sync, and not going to add this (before/after as steps), will consider improved visibility of these action blocks in the future
