### ISSUE TITLE
Thrown exceptions causes steps to fail, but not the whole journey

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#692]
If, to a journey, I try to fail a step with the code:

`throw("I ded")`

In the kibana UI I'll see a state where the step shows as failed, but the overall journey / check shows as passed.

If I use a playwright assertion, such as

`expect("I ded").toBe("ded")`

Both will fail as expected

**Comment by vigneshshanmugam** [comment]
Not sure how you are testing this one. But we have a test that covers this case - https://github.com/elastic/synthetics/blob/aedfc4b1e384e155f7ffd04b967eb31e127a75e8/__tests__/core/runner.test.ts#L125
