### ISSUE TITLE
Bundling of external NPM modules not working on `push`

### ISSUE THREAD

**Issue by arjun-1** [elastic/synthetics#693]
Currently I am bundling NPM module `totp-generator` in a synthetic journey as prescribed [here](https://github.com/elastic/synthetics/releases/tag/v1.0.0-beta.34).

After successfully pushing the tests (`npm run push ...`) to our Elastic Cloud, Kibana reports the following error instead of running the monitor:

```
Error: Cannot find module 'totp-generator'
- /tmp/elastic-synthetics-unzip-1831755341/journeys/journey-helpers.ts
- /tmp/elastic-synthetics-unzip-1831755341/journeys/login.journey.ts
- /usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/dist/loader.js
- /usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/dist/cli.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/tmp/elastic-synthetics-unzip-1831755341/journeys/journey-helpers.ts:2:1)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Module.m._compile (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/ts-node/src/index.ts:1618:23)
at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Object.require.extensions.<computed> [as .ts] (/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/node_modules/ts-node/src/index.ts:1621:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/tmp/elastic-synthetics-unzip-1831755341/journeys/journey-helpers.ts',
'/tmp/elastic-synthetics-unzip-1831755341/journeys/login.journey.ts',
'/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/dist/loader.js',
'/usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/dist/cli.js'
]
}
```

When running `npm run test` locally, the tests successfully run to completion. I am using version 1.0.0-beta.39 of @elastic/synthetics and version 8.4.2 of Elastic Cloud

**Comment by arjun-1** [comment]
Related seems to be that even local imports cannot be found, when importing them in helper modules. Only directly importing dependencies into the journey module works (which will also work for external modules)

**Comment by vigneshshanmugam** [comment]
@arjun-1 Apologies for the delay. Can you let me know how the folder is structured and paste a demo code of both the files `login.journey.ts` and `journey-helpers.ts`. 

Also, we had a similar bug #652. Could you try with our latest release which fixes the bug https://github.com/elastic/synthetics/releases/tag/v1.0.0-beta.40. Please let us know how it goes.

**Comment by vigneshshanmugam** [comment]
Closing as stalled, Please do report if you are still seeing any issues.

**Comment by renzedj** [comment]
I recently ran into a similar issue with a module I wrote to support my synthetic testing.

In my use case, I have a large number of identical journeys that I run against multiple URLs, so I wrote a factory class to generate the test and use parameters to pass things such as URL, test ID, etc. into the tests.

When I write the factory class as a module and import it into my test, it runs as expected when I execute it from the command line from my local machine. However, when I push it, it fails.

When I include the factory class in the journey file, it runs as expected. My assumption is that when I push, it is not importing the module file.

**Comment by vigneshshanmugam** [comment]
@renzedj Might be a bug on our bundler that is failing to recognize the imported module. We have not seen any issue related to the bundling, so if you can give a repro that would be great. Thanks.

**Comment by renzedj** [comment]
> @renzedj Might be a bug on our bundler that is failing to recognize the imported module. We have not seen any issue related to the bundling, so if you can give a repro that would be great. Thanks.

In looking at it in more detail, this may, in fact, be a different issue. If so, I can certainly open a new issue.

Here's a minimum example:

File: `journeys/journey-factory.journey.ts`:

```ts
import { JourneyFactory } from './modules/journey-factory';

const googleJourney = new JourneyFactory().createJourney();
googleJourney();
```

File: `journeys/modules/journey-factory.ts`:

```ts
import { journey, step, monitor, expect } from '@elastic/synthetics';

interface JourneyFunction {
  (): Promise<void>;
}

export class JourneyFactory {
  private env: string;  // Test environment

  createJourney(): JourneyFunction {
    return this.syntheticsJourney;
  }

  // Journey function
  syntheticsJourney = async (): Promise<void> => {
    journey(`google_factory_test`, ({ page, params }) => {
      monitor.use({
        id: '35a0908a-dac1-4c95-ba9c-28afbe1b4c07',
        schedule: 5,
        tags: ['google', 'factory', 'module', 'test',],
      });

      step('Open URL', async () => {
        await page.goto('https://www.google.com/');
        await expect(page.getByText('Google')).toBeTruthy();
      });
    });
  }
}
```

This test runs locally, when I execute it from the command line on my workstation with `npx @elastic/synthetics .`.When I look at the correct folder on the Agent, I see the following:

```
root@elastic-synthetics-agent-XXXXXXXXXX-XXXXX:/tmp/elastic-synthetics-unzip-XXXXXXXXXX/journeys# ls -l
total 0
drwxrwx--- 2 root root 32 Mar 19 14:04 modules
root@elastic-synthetics-agent-XXXXXXXXXX-XXXXX:/tmp/elastic-synthetics-unzip-XXXXXXXXXX/journeys# ls -l modules/
total 4
-rwxrwx--- 1 root root 2039 Mar 19 14:04 journey-factory.ts
root@elastic-synthetics-agent-XXXXXXXXXX-XXXXX:/tmp/elastic-synthetics-unzip-XXXXXXXXXX/journeys/modules#
```

When I examine the contents of `journey-factory.ts`, it corresponds to the module, I'm not able to find the actual journey file.

When the test runs on the agent, it generates the following error:

![image](https://github.com/elastic/synthetics/assets/81439124/429ac45e-b3ac-4fff-8a81-4fcac05c5e7f)
