### ISSUE TITLE
[Browser project monitors] No option for disabling monitor alerting

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/synthetics#698]
In 8.7.0, we are introducing alerting, with a toggle that allows you to turn alerting on and off for a particular monitor.

However, there is no way to overwrite alerting for browser project monitors.

We should update the types for the monitor configuration, found [here](https://github.com/elastic/synthetics/blob/main/src/dsl/monitor.ts#L45), so that `alerts` can be added to monitor.use without type errors.

The schema is as follows
```
{
   status: {
      enabled: boolean
   }
}
```

A TLS option likely coming later. 

I believe we may need a change on the Kibana side as well to support disabling alerting for browser project monitors. Further investigation is needed.

**Comment by paulb-elastic** [comment]
Linking https://github.com/elastic/synthetics/pull/713

**Comment by shahzad31** [comment]
closed via https://github.com/elastic/synthetics/pull/713

**Comment by paulb-elastic** [comment]
Post FF testing good
