### ISSUE TITLE
support playwright test assertions in synthetics

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#700]
+ We rely on the default `expect` library assertions which does not have the complete list of assertions that are supported by the Playwright test library. This would be confusing for users who are trying to run these playwright tests in the elastic globally managed infrastructure. 

+ Using the `plawyright-test/expect` assertions would require us to replace the current [expect](https://github.com/elastic/synthetics/blob/cbf4c4e388acb25c86a94e3c99ad516aee9f13e6/src/core/expect.ts) and keep the playwright version up to date #614

**Comment by jasonwhetton** [comment]
please support the standard playwright assertions this is really helpful not least for migrating existing tests.

**Comment by leweafan** [comment]
You are right we can't use our standard tests.
`TypeError: expect(...).toHaveCount is not a function`

**Comment by jasonwhetton** [comment]
hi, is there any plan to pick this up? having web first assertions is pretty much a necessity for using playwright in a stable way.... it seems odd that this isn't prioritised.

**Comment by paulb-elastic** [comment]
@jasonwhetton this is on our backlog and something we will look to add in the future, but we're just not able to focus on it right now.
