### ISSUE TITLE
validation with node_modules monitor examples

### ISSUE THREAD

**Issue by shahzad31** [elastic/synthetics#712]
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/3505601/223091207-9b760328-b22d-4451-aa4a-d311971fa73b.png">

**Comment by vigneshshanmugam** [comment]
I am not sure if this a bug. Seems like you linked the agent from your local folder and it kinda takes everything from there. We can add an option to ignore node_modules, but I don't see users running in to this problem.

**Comment by vigneshshanmugam** [comment]
Seems like we always had this issue, but since our templating logic was broken https://github.com/elastic/synthetics/commit/cbf4c4e388acb25c86a94e3c99ad516aee9f13e6 we never picked it up. Addressing that one, revealed the other bug.
