### ISSUE TITLE
Make `--url` optional for `locations` command

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#718]
When using `push`, the `--url` parameter is not needed because it’s contained in the `synthetics.config.ts` file.

However, when using the `locations` command, the `--url` param is needed or it only returns the [internally defined locations](https://github.com/elastic/synthetics/blob/main/src/locations/public-locations.ts).

It would be useful to only need to specify the `--auth` (or have it predefined in the environment) and if there is a `project.url` defined in `synthetics.config.ts`, then use that by default (there by outputting any private locations too).  It should still be possible to override this using `--url`, but it should behave more consistently with `push`.

ACs:
* Running `locations` on it’s own, returns the [internally defined locations](https://github.com/elastic/synthetics/blob/main/src/locations/public-locations.ts)
* Running `locations --auth ...`
  * If `project.url` is defined in `synthetics.config.ts`, CLI returns the locations from that Kibana instance (for public and private locations)
  * If `project.url` is NOT defined in `synthetics.config.ts`, CLI return the [internally defined locations](https://github.com/elastic/synthetics/blob/main/src/locations/public-locations.ts)
* Running `locations --auth ... --url ...` returns the locations from that Kibana instance (for public and private locations)
  * Effectively ignoring any `project.url` definition in `synthetics.config.ts`

**Comment by shahzad31** [comment]
it's working for me without adding url option

```
➜  test-projects git:(locations-url) npx @elastic/synthetics locations
Available locations: 
   * japan
   * india
   * singapore
   * australia_east
   * united_kingdom
   * germany
   * canada_east
   * brazil
   * us_east
   * us_west
   
Set default location for monitors via
  - Synthetics config file 'monitors.locations' | 'monitors.privateLocations' field
  - Monitor API 'monitor.use({ locations: ["japan"], privateLocations: ["custom-location"] }')

```

**Comment by paulb-elastic** [comment]
To clarify @shahzad31's point - that's only for the main locations (generated internally by Synthetics from https://github.com/elastic/synthetics/blob/main/src/locations/public-locations.ts), but doesn't include the private locations without `--url` being specified (even though it's in the `synthetics.config.ts` file).
