### ISSUE TITLE
`push` does not send params for lightweight monitors

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#725]
When pushing lightweight project monitors, it does not include the params defined in either `synthetics.config.ts` or from `--params`.  With the implementation added in https://github.com/elastic/kibana/issues/147467, that means the behaviour is different between browser monitors and lightweight monitors.

i.e. The `push` command should also include the params defined as they can be for browser monitors (config file, `--params`) when sending to Kibana.  The priority of the solution should be the same as for browser monitors (see https://www.elastic.co/guide/en/observability/master/synthetics-params-secrets.html#synthetics-basic-params), i.e.

1. Global params in Kibana
2. Then `synthetics.config.ts`
3. Then `--params` defined in `push`

Ensure the order remains consistent and as defined above with both browser and lightweight monitors after this change.

**Comment by awahab07** [comment]
**Post FF Testing**

LGTM as covered in https://github.com/elastic/kibana/pull/157226#issuecomment-1548424466.
