### ISSUE TITLE
[CI] fix release script to be based on `semantic release`

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#763]
+ Now that we dropped the beta label for the releases, we have to make releases based on the `semantic release` and also version it based on our PR conventional commit tags. 
+ To make it non-blocking, I dropped the beta flags from the pipeline to make sure we dont do accidental publishing. 

Semantic release - https://github.com/semantic-release/semantic-release

**Comment by vigneshshanmugam** [comment]
Pinging @elastic/observablt-robots

**Comment by v1v** [comment]
Hey @vigneshshanmugam ,

I'm not sure what's needed from our side here, I see https://github.com/elastic/synthetics/pull/762 was already merged.

Do you mean adding some linting so PRs and commits are following the same release as done with https://github.com/elastic/apm-agent-rum-js/blob/main/scripts/lint-commits.sh ?

**Comment by vigneshshanmugam** [comment]
@v1v We are not blocked, for now we can work with manually doing it from Developers machine. So whatever works for your team. Thanks for the help.

**Comment by paulb-elastic** [comment]
@vigneshshanmugam @v1v is there still work to do here?

**Comment by vigneshshanmugam** [comment]
Yes we are still blocked on this and releasing manually for now which is not desirable for long time. Not everyone on the team also has access to the npm.

**Comment by reakaleek** [comment]
Hey @vigneshshanmugam and @paulb-elastic,

sorry this got lost, @v1v is on parental leave.

I will assign myself and ping @cachedout for awerness.

**Comment by reakaleek** [comment]
Hi, 

I did some research on semantic-release and I have some questions.


### Conventional COmmits <-> Squashing

According to https://github.com/semantic-release/semantic-release/issues/792, semantic-release does not play well with squash merges.

We could then lint the PR title. However, this doesn't seem too reliable also. Because you can change the message before clicking on merge.

Also, some of the data might get lost when doing multiple commits in a PR.

In the comments there is also this [plugin](https://github.com/romap0/semantic-release-unsquash) mentioned, that could potentially solve this problem. But I think it has the same problem, that anyone could change the commit message in the UI before clicking on merge.

What are your thoughts about this?

### Release trigger

The recommended trigger is on push to the `main`, `next`, or `beta` branch.
Do we also want this? Or should it still be a manual trigger?

**Comment by vigneshshanmugam** [comment]
Thanks for taking time to check the release issue @reakaleek 

> We could then lint the PR title. However, this doesn't seem too reliable also. Because you can change the message before clicking on merge.

We have always relied on squash merges and have always been careful when it comes to the PR title as we wanted to follow the conventional commits format. 

To be in safer hands, I would also recommend if we can lint the PR message for the conventional commit format which can be done with https://github.com/conventional-changelog/commitlint.

> The recommended trigger is on push to the main, next, or beta branch.
Do we also want this? Or should it still be a manual trigger?

We would like the release trigger to be manual.

**Comment by reakaleek** [comment]
Hey @vigneshshanmugam,

Sorry for the delay. I just wanted to let you know that we added this issue to our current iteration.
Hence, I will be able to work on this in the next 1-3 weeks.

**Comment by reakaleek** [comment]
@vigneshshanmugam 

How do we want to treat the CHANGELOG.md file?

I understood, we can use the @semantic-release/changelog plugin in combinastion with the @sematic-release/git plugin.

However, these plugins would automatically commit to the main branch.

There is a risk that this behaviour is not compliant with SLSA, because there is a rule that no unreviewed code should be committed.

Potentially, this is some gray area. As the CHANGELOG.md file does not change the behaviour of the app. But this needs to be clarified.

Shall we continue without an automated changelog file for now?

**Comment by vigneshshanmugam** [comment]
Hi @reakaleek,

We are not using the `CHANGELOG.md` file actively, we heavily rely on the Releases page - https://github.com/elastic/synthetics/releases and adding important features/bugs. So we can basically skip auto-generation if it makes it easier.

**Comment by reakaleek** [comment]
TIL: semantic-release does not support 2fa with OTPs.

In NPM there is a concept of "[Automation Tokens](https://docs.npmjs.com/creating-and-viewing-access-tokens)", which are able to bypass the 2fa, without remove 2fa from the NPM account.

I'm trying to find out if this is something we can do, or if 2fa is a hard requirement.

**Comment by reakaleek** [comment]
# Alternatives

semantic-release does not support 2FA. There some possible alternatives:

## Only use semantic-release partially and manually run `npm publish`

I can disable the `@semantic-release/npm` plugin and do the publishing steps manually.

it would looks something like this:

```shell

npx semantic-release # with disabled npm plugin

# git tag and github release + generated release notes will be created

new_version=$(<somehow get the generated version>)

npm version ${new_version} --no-git-tag-version

npm publish --otp=<otp>

```

## Automation Token

NPM has the concept of "Automation Tokens", these are tokens that you can create in the NPM UI which can bypass 2FA, without remove 2FA from the account.

![Image](https://github.com/elastic/synthetics/assets/16325797/eab8afac-c852-4be6-8b2c-40aa8239abca)

## Custom semantic-release plugin

We can fork https://github.com/semantic-release/npm and add the ability to provide an OTP.

The plugin is basically a wrapper around `npm publish` 

```javascript
const result = execa(
      "npm",
      ["publish", basePath, "--userconfig", npmrc, "--tag", distTag, "--registry", registry],
      { cwd, env, preferLocal: true }
    );
```

https://github.com/semantic-release/npm/blob/cc64b42254487bade03311acbda4b4dace7faee5/lib/publish.js#L25

and we can add the `--otp` option somehow.


## Contribute to semantic-release

We could contribute to semantic-release to get this behaviour, but it's questionnable if they even want this and if a change like this will ever be merged.

**Comment by v1v** [comment]
> Automation Token

I'm not onboarded to use this approach but using the 2FA so no matter who has access to the token they cannot do much without accessing the TOTP. The existing TOTP is already secured and the access is restricted/controlled. While creating an "Automation token" cannot warranty the token cannot be exposed by accident or even being targeted. 

> Only use semantic-release partially and manually run npm publish

Can you elaborate what manually means? If it will be automated in a script, I think this can unblock this issue and use the existing security model around publishing artifacts with the 2FA.

> Custom semantic-release plugin

If the previous approach is functional and simple, I'd say that can unblock this issue.

> Contribute to semantic-release

It sounds we might not get the PR approved and using a forked version might cause some other issues when integrating changes from the upstream.

**Comment by reakaleek** [comment]
> Can you elaborate what manually means?

Ah, yes with manually I mean "without using semantic-release" but doing `npm publish` in a workflow step.

**Comment by reakaleek** [comment]
dry run of the release workflow: https://github.com/elastic/synthetics/actions/runs/6163806481/job/16728166842
