### ISSUE TITLE
support node 16 and remove strict engine verification

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#789]
### How its right now
+ Currently synthetics agent targets `node18` when bundling and publishing the library to the NPM - https://github.com/elastic/synthetics/blob/117c1b3227932c645050fd66e013b6c981baa57b/tsconfig.json#LL10C24-L10C24
+ We also set the engine to `>node18` in the `package.json` file since we want to enforce the same version on the Heartbeat side when running monitors. 

### Outcome
+ Users would like to use the agent on `Node 16` which is still support and EOL in September 2023. Kibana still is on node 16 and cannot use the agent as it is forcefully doing the engine check.
+ Change target on the TS config.

**Comment by shahzad31** [comment]
Not needed anymore sinc kibana is being upgraded to node 18
