### ISSUE TITLE
we should support --no-headless as base option for cli runner

### ISSUE THREAD

**Issue by shahzad31** [elastic/synthetics#799]
Sometime back we removed `--no-headless` as an option to run things locally 

IMO we should add it back. Using `--playwright-options '{"headless":false}"` is so hard to use and it's not easy to find that it's supported via that option without visiting playwright docs. 

It's natural to expect with any browser runner to have --no-headless command to run a test locally for testing.

**Comment by paulb-elastic** [comment]
@elastic/uptime a reminder for folks to update this for the core flags that would be useful (i.e. more than just `--no-headless`, but without duplicating all PW options)
