### ISSUE TITLE
Update Synthetics to the latest version of Playwright/Chromium and Release

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#822]
To keep the Synthetics Agent up to date, upgrade to the latest version of Playwright/Chromium

- [x] Update to the latest version of Playwright/Chromium
- [x] Release a new version of the Synthetics Agent with the update

**Comment by vigneshshanmugam** [comment]
We did cover 1.38 - https://github.com/elastic/synthetics/pull/834. Haven't released anything yet.

**Comment by vigneshshanmugam** [comment]
Released 1.38.1 PW version with `1.5.0`- https://github.com/elastic/synthetics/releases/tag/v1.5.0 Marking this as completed.
