### ISSUE TITLE
Having synthetics.config.ts playwrightOptions.headless: false has no effect, check is executed in headless mode

### ISSUE THREAD

**Issue by kazagz** [elastic/synthetics#837]
**Versions affected:** *>= 1.0.0* including *1.4.0*
**Last seen working:** *v1.0.0-beta.46*

*synthetics.config.ts*
```ts
import type { SyntheticsConfig } from "@elastic/synthetics";

export default (env: string) => {
  const config: SyntheticsConfig = {
    // other stuff
    playwrightOptions: {
      headless: false,
    },
    // other stuff
  };

  return config;
};

```
Having this setting to true / false has no effect, script will always be executed in headless mode. The only way to run it in headfull mode is to pass --no-headless option when running script (in versions that support --no-headless).

It was originally reported in https://github.com/elastic/synthetics/issues/740 and supposedly fixed in https://github.com/elastic/synthetics/pull/741, but it's not fixed.

**Comment by shahzad31** [comment]
@kazagz yes i already have a PR up. we were expecting default would be undefined but it seems like option with --no had default value true in commander lib 

https://github.com/elastic/synthetics/pull/838
