### ISSUE TITLE
Issue with Default Chromium Version in Playwright

### ISSUE THREAD

**Issue by EmilioHerreraSoukup** [elastic/synthetics#846]
## Issue with Default Chromium Version in Playwright

It seems `chromium-1076` is set as the default. However, I consistently encounter an issue where the system fails to locate this version. When executing `npx playwright install`, it installs a newer version. My current workaround involves manually specifying the path in the `playwrightOptions`:

```javascript
playwrightOptions: {
  ignoreHTTPSErrors: false,
  executablePath: '../../Caches/ms-playwright/chromium-1080/chrome-mac/Chromium.app/Contents/MacOS/Chromium',
},

**Comment by vigneshshanmugam** [comment]
Thanks for raising the issue, Could you tell us how you are using this library `@elastic/synthetics` and what was the version used to test this issue?

**Comment by EmilioHerreraSoukup** [comment]
Hi!, thank you for the response! I am using `"@elastic/synthetics": "1.4.0"

**Comment by vigneshshanmugam** [comment]
When you install `npm install @elastic/synthetics`, Chromium gets auto installed at the PW specified location, Could you please help us with the steps you followed and how you are using the library to run the test suite. Thanks.

**Comment by vigneshshanmugam** [comment]
Closing as there has been any activity. Please do reopen if the issue persists.
