### ISSUE TITLE
[CI] fix release script to take `stack_release` input

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#849]
+ The new release process works smoothly and published the latest changes to NPM, but has few issues

- `is-stack-release` is not working as expected, Had to manually do tag the last release `1.5.0`
- Notifications were not sent to the Slack channel. 
- Latest dist tag is not necessary as `npm publish` would automatically mark the last published as latest. 

Release - https://github.com/elastic/synthetics/actions/runs/6489571541/job/17624055402

I believe the bug is happening because the `workflow input` where empty values are not considered falsy.

**Comment by vigneshshanmugam** [comment]
@reakaleek @v1v FYI

**Comment by v1v** [comment]
@vigneshshanmugam , I'm gonna work on this, so I'll keep you updated with my findings and raise the fix - if I can find it :)

**Comment by v1v** [comment]
I think https://github.com/actions/runner/issues/1483 is the main issue. let me put a fix with a string comparation.

**Comment by v1v** [comment]
@vigneshshanmugam 

> Latest dist tag is not necessary as npm publish would automatically mark the last published as latest.


Do you mean that [Create 'latest' dist-tag](https://github.com/elastic/synthetics/blob/e27f71c22a925d1be0723f21daff5bd29a25a067/.github/workflows/release.yml#L51-L53) is not required?

**Comment by vigneshshanmugam** [comment]
@v1v Yeah, When we publish to NPM, that would be set as the latest tag.

**Comment by v1v** [comment]
https://github.com/elastic/synthetics/pull/855 is the one to remove the latest dist tag

**Comment by v1v** [comment]
@vigneshshanmugam , I'll close this now after merging all the PRs, please reach us if you see anything else when running a new release. Thanks

**Comment by vigneshshanmugam** [comment]
@v1v Thanks Victor for the quick turnaround.

**Comment by vigneshshanmugam** [comment]
@v1v Reopening as a result of https://github.com/elastic/synthetics/actions/runs/6635781459/job/18027249375

**Comment by v1v** [comment]
https://github.com/elastic/synthetics/pull/858 is the fix with the quoting

**Comment by v1v** [comment]
Closing this now, feel free to re-open it
