### ISSUE TITLE
'push' fails if upload takes more than 60 seconds

### ISSUE THREAD

**Issue by kazagz** [elastic/synthetics#851]
https://github.com/elastic/synthetics/blob/f75c4705b30f30a2b33b2d20e82b18a65adfa0e6/src/push/request.ts#L51

We have quite small project with about 10 journeys and 10 lightweight scripts, but it's expected that project will grow to have more than hundred different scripts in it. Existing implementation of 'push' fails even with existing project, because it takes more than hardcoded 60 seconds to perform operation. As far as I can tell there's no option to change this timeout, updating `synthetics.config.ts` with something like this doesn't work:
```ts
import { setGlobalDispatcher, Agent } from "undici";

setGlobalDispatcher(
  new Agent({
    headersTimeout: 5 * 60 * 1000,
  }),
);
```

Error if `push` takes more than 60 seconds:
```bash
HeadersTimeoutError: Headers Timeout Errors)
    at Timeout.onParserTimeout [as callback] (/***/***/git/synthetics-journeys/node_modules/undici/lib/client.js:931:28)
    at Timeout.onTimeout [as _onTimeout] (/***/***/git/synthetics-journeys/node_modules/undici/lib/timers.js:20:13)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}
```
`push` should have timeout options or even better - refactored, so that all monitors are not pushed in single bulk request.

And no, it is not possible to have multiple small projects, all journeys should exist in single project.

**Comment by shahzad31** [comment]
@kazagz can you please describe your setup? i mean are you using public locations, private locations. Generally we expect push  command to be very very fast. It seems like your setup is too slow in some aspect. I would like to understand more on why it might be taking so long to push command. Either kibana is too slow or may es. Does your kibana and ES are on the same network?

**Comment by kazagz** [comment]
@shahzad31 we're using private locations and have self-managed / on-premise platform. Monitors are pushed to Kibana from CI/CD pipeline. Kibana and Elastic are on same network. Pipeline and Kibana / Elastic are not on same network in a sense that Kibana server and CI/CD agents are in different segments, but they are on same datacenters and there's no issues with network latency etc. 
Our journeys use some external npm packages in them so bundles would be larger than those that only contain out-of-the-box `@elastic/synthetics` packages. 

We might in fact need some optimizations for our Kibana and Elastic, because these timeouts do tend to happen at times when there's some other workload being done by Kibana / Elastic, but that won't solve the issue permanently. Example, now on 'good' run (with Kibana / Elastic idle) it would take about 10 seconds to push monitors. On 'bad' run it would take about 70 seconds. Even if we do run pipeline on only 'good' timeslots, our goal is to have hundreds of journeys in project (x10 than we have now), which means that even on 'good' run it would almost certainly exceed 60 seconds for command to complete. I would feel much better if there would be an option to customize timeout or global configuration for `undici`.

**Comment by shahzad31** [comment]
@kazagz i have merged a [PR](https://github.com/elastic/synthetics/pull/852) to increase timeout to 120sec which aligns it with default kibana API timeout.  We will discuss internally to make it configurable , in that case we will also need to change kibana API timeout.
