### ISSUE TITLE
max_redirects lightweight configuration option error

### ISSUE THREAD

**Issue by felipeavilis** [elastic/synthetics#857]
When setting "max_redirects" lightweight configuration option im getting an error:
```
> Monitor Diff: Added(0) Updated(1) Removed(0) Unchanged(0)
✖ Erroring or updating 1 monitor (500ms)
   > Couldn't save or update monitor because of an invalid configuration.: monitor(my-link-id)
       Invalid value "2" supplied to "max_redirects"
```
Its a HTTP monitor. Here is my heartbeat.yml
```
heartbeat.monitors:
  - type: http
      name: Monitor Name
      id: my-link-id
      enabled: true
      urls: "https://mylink.com"
      max_redirects: 2
      schedule: "@every 5m"
      timeout: 16s
      alert.status.enabled: true 
```
What am i doing wrong? I followed this link guide:
https://www.elastic.co/guide/en/observability/current/synthetics-lightweight.html#synthetics-lightweight-http

**Comment by felipeavilis** [comment]
UPDATE: The documentation says that the option type is NUMBER. I tried to use as a string, with double quotes ("") and it worked.

**Comment by vigneshshanmugam** [comment]
@felipeavilis Thanks for raising this issue - We have a fix already for this one - https://github.com/elastic/kibana/pull/169087. Will be updated in the new Kibana release. Thanks once again.
