### ISSUE TITLE
[CLI] Not able to target a project on push

### ISSUE THREAD

**Issue by beimingw** [elastic/synthetics#866]
The [documentation](https://www.elastic.co/guide/en/observability/current/synthetics-command-reference.html) indicates it is possible to run push against a specific project using `--project`. But that does not seem to be valid:  

```
node@950d19cc4b1d:~/projects$ npx @elastic/synthetics --version
1.5.2

node@950d19cc4b1d:~/projects$ npx @elastic/synthetics push --project test
error: unknown option '--project'
```

I also don't see the option in `src/cli.ts`. Is this a documentation error?

**Comment by vigneshshanmugam** [comment]
@beimingw Apologies for the confusion. The docs are incorrect. You can push a project under a different id by passing `--id` flags. 

```
npx @elastic/synthetics push --id test
```

Will open a PR to update the docs. Thanks for bringing it to our notice.

**Comment by beimingw** [comment]
@vigneshshanmugam Thanks that does work. 

However, it still needs to be executed inside of the target project directory. I was expecting this could be used at the parent directory in order to target different projects, and can't see a use case of this parameter in current form.

**Comment by vigneshshanmugam** [comment]
Ahh, That is not how project monitors are structured and how push command works in general. 

Push command pretty much works similar to how a `git push` would work. It tracks all the changes from the current repository and updates the remote Kibana instance with all the updates including creation/deletes. Projects are basically used for grouping subdirectories, If you intend to only push relevant monitors, then you would need to push from a particular project directory. 

Let us know if you have any feedback.

**Comment by beimingw** [comment]
Thanks I get it now.
