### ISSUE TITLE
No journey details are captured if running in new context

### ISSUE THREAD

**Issue by kazagz** [elastic/synthetics#867]
Sometimes there is need to start browser with context that is different from default defined in `synthetics.config.ts`. Like this:
```ts
import { step, monitor, journey, Page, ChromiumBrowserContext } from "@elastic/synthetics";

journey("My journey", ({ browser }) => {
  monitor.use({
    ...myMonitorConfiguration,
  });

  let page: Page;
  let context: ChromiumBrowserContext;

  step("Open new context", async () => {
    context = await browser.newContext({
      ...myBrowserConfiguration,
    });
    page = await context.newPage();
  });

  step("Open page", async () => {
    await page.goto("https://example.com/");
  });
});
```
Pushing this to Kibana works fine and journey is executed, steps are listed properly. But there are no network requests or screenshots recorded for this new context, all you get step with blank page. It would be great if you could either specify custom context in journey options or if all contexts would get recorded. 

Screenshot attached.
![context](https://github.com/elastic/synthetics/assets/44868633/23e934b7-f1b8-4731-97ab-5c3340d85014)

**Comment by shahzad31** [comment]
Hello @kazagz all you need is , we may have a known issue that playwright options you pass via below statement may not work locally but they will once you push to kibana and at execution time

```
monitor.use({
    ...myMonitorConfiguration,
  });
```

playwright options you pass via above statement will be passed to the context being used by journey. We don't support creating a new context within journey. Like you rightly pointed out , network data etc will not be captured.

**Comment by shahzad31** [comment]
there is some more context provided here by @vigneshshanmugam 

https://discuss.elastic.co/t/use-environment-variables-from-kubernetes-pod-in-elastic-synthetics/345396/8?u=shahzad31

**Comment by kazagz** [comment]
@shahzad31 thanks, somehow I had missed this parameter. That's fine if locally it has no effect on monitor.
