### ISSUE TITLE
[Enhancement Request] Allow Faster Invervals

### ISSUE THREAD

**Issue by MakoWish** [elastic/synthetics#901]
We are slowly starting to leverage Synthetics more, with plans to migrate off Heartbeat, but one thing that is preventing us from moving a lot of monitors from Heartbeat to Synthetics is the polling intervals. With Heartbeat, we have all our ICMP monitors configured to ping every 10 seconds. With Synthetics, the quickest interval you can select is one minute. IMHO, that is nowhere near a tight enough resolution for accurate and prompt alerting of issues. Most of our alerting rules are along the lines of "down three times within one minute", but that is not possible if you can only check every one minute. The interval really needs to be more configurable.

**Comment by MakoWish** [comment]
Nothing on this? We really want to migrate to Synthetics, but the "1 minute" minimum frequency just won't do.

**Comment by paulb-elastic** [comment]
Lightweight monitors now have options for 10 and 30 seconds (see https://github.com/elastic/synthetics/pull/932):

![image](https://github.com/user-attachments/assets/391c9e37-b897-4642-b994-4cadf488fb9d)

**Comment by MakoWish** [comment]
I am not seeing that. What version was this introduced in? I don't see a version tag on that PR. We are on 8.14.1, and all monitors (Multistep, Single Page, HTTP Ping, TCP Ping, and IMCP ping) only allow down to 1 minute.

**Comment by paulb-elastic** [comment]
@MakoWish good point, my apologies
I see that Shahzad has [replied to your question](https://github.com/elastic/synthetics/pull/932#issuecomment-2275114938), for anyone else following along, it will be available in 8.15.0

**Comment by shahzad31** [comment]
This is already shipped
