### ISSUE TITLE
Hide API key during CLI init dialogue  and optionally export to env, combine Cloud ID and Kibana URL prompt

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics#906]
When the user creates a new project, Synthetics will prompt them for their API key.

Today, this requires pasting the API key (and including it in plaintext). This looks like:

```shell
➜ npx @elastic/synthetics init
> Initializing Synthetics project in '.'
✔ Do you use Elastic Cloud (Y/n) · false
✔ What is the url of your Kibana instance · http://127.0.0.1:5601
✔ What is your API key · <blah>
```

After the project scaffolding is created, `npm run push` will not work unless the user also exports `SYNTHETICS_API_KEY` or includes it as an `env` arg when running the command.

For tasks like demoing Synthetics or running this setup in any kind of communal way, this requires showing the API key in plaintext. It would be better if, when the user pasted their API key, the prompt did not display it (which is standard for typing/pasting passwords in CLI prompts).

It would also be a useful addition to have the option to have Synthetics export the API key to the path at the end of the dialogue so the `npm run push` command will work straight away without additional configuration. This is something I, as a frequent user, forget to do plenty of the time and is probably confusing for users.

Additionally, we should combine the question about the user's Cloud ID and their Kibana URL into a single question and translate the Cloud ID to a Kibana URL for them. This lets us skip a question and streamlines the flow.

**Comment by vigneshshanmugam** [comment]
I am generally against the idea of changing the Environment variables via scripts unless we know absolutely what we are doing. 

In the synthetics case doing so would make it harder to debug issues if the user has multiple projects setup that requires different authkeys based on the project settings they are pushing. But I also get the sense, this is really frustrating that even after giving the APIKey, we still expect users to pass it when doing `npm run push`. To fix that, I propose we improve the push command generation and add the `--auth <value>` at the end of project scaffolding and so the `npm run push` command will work straight away without additional configuration

**Comment by vigneshshanmugam** [comment]
`--auth` idea wont work as we it would write the APiKey in plain text on the package.json script which is not good from the security perspective. 

Only thing we could do is to change the documentation and mention the users to export it themselves to be in safer side.

**Comment by vigneshshanmugam** [comment]
The best solution to solve both of the concerns raised is - https://github.com/elastic/synthetics/issues/603, Which works for both multiple projects and easier onboarding.
