### ISSUE TITLE
Typescript definitions not available for expect

### ISSUE THREAD

**Issue by ivosh** [elastic/synthetics#917]
Dear,

Please could you fix the following line in 
https://github.com/elastic/synthetics/blob/main/src/core/expect.ts#L42

so that the Typescript definitions are actually available for `expect`.
The original line points to a non-existing location.

Original:
```
export const expect: typeof import('../../bundles/node_modules/playwright/types/test').expect =
```

Fixed:
```
export const expect: typeof import('../../node_modules/playwright/types/test').expect =
```

The impact of this issue is that the Typescript definitions for `expect` are not available for IDE, `eslint` etc.
This gives a lot of false warnings causing developers confusion.

**Comment by vigneshshanmugam** [comment]
Thanks for reporting @ivosh, Good find.

**Comment by vigneshshanmugam** [comment]
Closed by #923

**Comment by ivosh** [comment]
@vigneshshanmugam Thank you for fixing this (small) issue and for releasing a fix in a couple of days. I confirm linting now works!

**Comment by vigneshshanmugam** [comment]
@ivosh Thanks again for testing and reporting the issue.
