### ISSUE TITLE
Fix push command to only push monitors that were modified/deleted

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#936]
+ Currently we push all the monitors when pushing monitors, even when the monitor configuration is unchanged which causes confusion to all users. We can filter down and push the modified monitors (Added/Updated/Deleted) ones instead of pushing the all the unchanged monitors as well - https://github.com/elastic/synthetics/blob/21b4b2f4b9243be04bad8105048ef398970a83f7/src/push/index.ts#L93

+ Same is also applicable to deleted monitor list.

**Comment by nerophon** [comment]
The user has reported that this also causes performance problems:
> Some extra info which may help relating to that bug and the API: when using these APIs to push to Kibana, the memory usage of the KB nodes goes up considerably (and is why i noticed we should up our kb memory). I'm not sure if these APIs can be optimized in any way to reduce this, but a bug like this means that if we have 1000 monitors in a bulk push and only 1 monitor is added, it will actually push all 1000, which will effect the performance of the KB nodes during and after the time of the push. So I believe this bug also effects performance in addition to "confusing" users.
