### ISSUE TITLE
Issue with CLI push after upgrading to 1.14.0

### ISSUE THREAD

**Issue by ameindel** [elastic/synthetics#968]
Hello,

After upgrading from 1.11.1 to 1.14.0, our pipeline encountered an error when attempting to push synthetics to our self-hosted Elastic cluster.

**Here is the CLI command used:**
npx @elastic/synthetics push --auth [REDACTED] --url https://kibana.our.happy.little.cluster/ --pattern ".titansandbox." --id observability-titan-sandbox --yes

**Here is the error I encountered:**
`TypeError: Cannot read properties of undefined (reading 'length')
    at validateSettings (C:\Git\observability-synthetics\node_modules\@elastic\synthetics\src\push\index.ts:230:20)
    at validatePush (C:\Git\observability-synthetics\node_modules\@elastic\synthetics\src\push\index.ts:205:3)
    at Command.<anonymous> (C:\Git\observability-synthetics\node_modules\@elastic\synthetics\src\cli.ts:216:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Here is the suspected breaking change (v1.13.0):**
https://github.com/elastic/synthetics/commit/cce2844943614fb434255e6ed9ef066ecdea2462#diff-b688b09742f54428b94db9d34df92d1190d19c7c153b44c70bcdde60e2a1f1fbR230

src/push/index.ts line 230

**Additional info:**
For the 'locations' property, it is enforcing ("japan" | "india" | "singapore" | "australia_east" | "united_kingdom" | "germany" | "canada_east" | "brazil" | "us_east" | "us_west")[] | undefined, however, our locations names are customized and do not match with this enforcement.

I'll try downgrading to v1.12.1 as a workaround.

Please let me know if you need any additional information.

Thank you!

**Comment by vigneshshanmugam** [comment]
@ameindel Thanks for raising the issue, Could you share your `syntheitcs.config.ts` file? 

> however, our locations names are customized and do not match with this enforcement.

Are you running monitors on Globally managed locations or Private locations?

**Comment by vigneshshanmugam** [comment]
I was able to reproduce the issue by passing only the private location option. Thanks for raising it.

**Comment by ameindel** [comment]
Thanks for the quick response, @vigneshshanmugam. We're running on Private Locations. Please let me know if you still need me to share the  synthetics.config.ts file.

**Comment by vigneshshanmugam** [comment]
Np, all good, the issue has been resolved. We will do a release next week. Thanks again for reporting.
