### ISSUE TITLE
Issues when trying to push Synthetics tests up to an Elastic dashboard by means of tags

### ISSUE THREAD

**Issue by davidlyons1** [elastic/synthetics#979]
I am trying to push Synthetic tests up to an Elastic dashboard using tags. 
In my example I have tagged a number of tests with the tag "dev" and using the following syntax 

npx @elastic/synthetics push --auth <<auth key>>  --url <<url>> --tags dev

However I am receiving the error:

**Aborted. Invalid CLI flags.
Tags and Match are not supported in push command.**

Am I using the wrong syntax? is there an alternative method I can use? The issue is preventing me from having a repository where I can cherry pick which tests I wish to push up to different envirnments. Currently the push command pushes up every single test in my repo irrespective of tags.

Many Thanks in advance.

David Lyons.

**Comment by vigneshshanmugam** [comment]
Tags/Match options has been added to the push command in version `1.9.0` https://github.com/elastic/synthetics/pull/913, Please update your synthetics cli package by `npm install -g @elastic/synthetics`and try again.
