### ISSUE TITLE
Elasticsearch lightweight monitors unable to use params

### ISSUE THREAD

**Issue by fabry00** [elastic/synthetics#980]
I have a lightweight monitor defined in my @elastic/synthetics project defined as follow:

    heartbeat.monitors:
     - type: http
       name: "XXXXX"
       id: "XXXX"
       enabled: true
       urls: ["${my_url}"]

and my synthetics.confing.ts is 

    export default (env) => {
       const config: SyntheticsConfig = {
         params: {
           my_url: "https://test.com/api/test",
         },
         playwrightOptions: {
           ignoreHTTPSErrors: false,
         },
        
         monitor: {
          schedule: 10,
          locations: [],
          privateLocations: ["dev"],
        },
        project: {
          id: "monitoring",
          url: "https://kibana.net",
          space: "myspace",
        },
      }
      if (env !== "customenv") {      
      }
      return config
    }

when I push the monitors with the following command

    NODE_TLS_REJECT_UNAUTHORIZED=0 NODE_ENV="customenv" SYNTHETICS_API_KEY=ccccc== npx @elastic/synthetics push

I get:

    Error
       > Invalid Heartbeat configuration: monitor(XXXX)
           `http` project monitors must specify a valid URL for field `monitor.urls` in version `8.15.0`. Your monitor definition with ID `XXXX` was not saved.

**Comment by shahzad31** [comment]
@fabry00 thanks for using Elastic/Synthetics. 

We just fixed this bug few weeks ago and it was backported to 8.15.4 as well, release is hopefully around the corner

https://github.com/elastic/kibana/pull/197797

**Comment by vigneshshanmugam** [comment]
Closing as the bug has been fixed and will be released in the coming week as pointed out.

**Comment by fabry00** [comment]
@vigneshshanmugam  has this been fixed in 8.16.0? I just updated to 8.16.0 and I get inconsistent behaviour

**Comment by vigneshshanmugam** [comment]
> I get inconsistent behaviour

can you share more about what you are seeing and also an example if its different from the one you have on description? Thanks.
